In [1]:
import pandas as pd
import numpy as np

In [2]:
data=pd.read_csv(r"C:\Users\DELL\Downloads\Houseprice_by_City.csv")
data

,POSTED_BY,UNDER_CONSTRUCTION,RERA,BHK_NO.,BHK_OR_RK,SQUARE_FT,READY_TO_MOVE,RESALE,City,LONGITUDE,LATITUDE,TARGET(PRICE_IN_LACS)
0,Owner,0,0,2,BHK,1300.236407,1,1,Bangalore,12.969910,77.597960,55.0
1,Dealer,0,0,2,BHK,1275.000000,1,1,Mysore,12.274538,76.644605,51.0
2,Owner,0,0,2,BHK,933.159722,1,1,Bangalore,12.778033,77.632191,43.0
3,Owner,0,1,2,BHK,929.921143,1,1,Ghaziabad,28.642300,77.344500,62.5
4,Dealer,1,0,2,BHK,999.009247,0,1,Kolkata,22.592200,88.484911,60.5
...,...,...,...,...,...,...,...,...,...,...,...,...
29446,Owner,0,0,3,BHK,2500.000000,1,1,Agra,27.140626,78.043277,45.0
29447,Owner,0,0,2,BHK,769.230769,1,1,Lake View Recidency,39.945409,-86.150721,16.0
29448,Dealer,0,0,2,BHK,1022.641509,1,1,Jaipur,26.928785,75.828002,27.1
29449,Owner,0,0,2,BHK,927.079009,1,1,Chennai,12.900150,80.227910,67.0
29450,Dealer,0,1,2,BHK,896.774194,1,1,Jaipur,26.832353,75.841749,27.8

In [56]:
data.head(10)

,POSTED_BY,UNDER_CONSTRUCTION,RERA,BHK_NO.,BHK_OR_RK,SQUARE_FT,READY_TO_MOVE,RESALE,City,LONGITUDE,LATITUDE,TARGET(PRICE_IN_LACS)
0,Owner,0,0,2,BHK,1300.236407,1,1,Bangalore,12.969910,77.597960,55.0
1,Dealer,0,0,2,BHK,1275.000000,1,1,Mysore,12.274538,76.644605,51.0
2,Owner,0,0,2,BHK,933.159722,1,1,Bangalore,12.778033,77.632191,43.0
3,Owner,0,1,2,BHK,929.921143,1,1,Ghaziabad,28.642300,77.344500,62.5
4,Dealer,1,0,2,BHK,999.009247,0,1,Kolkata,22.592200,88.484911,60.5
5,Owner,0,0,3,BHK,1250.000000,1,1,Kochi,10.033280,76.282571,42.0
6,Dealer,0,0,3,BHK,1495.053957,1,1,Jaipur,26.916347,75.795600,66.5
7,Owner,0,1,3,BHK,1181.012946,1,1,Mohali,30.740000,76.650000,52.0
8,Dealer,0,1,2,BHK,1040.000000,1,1,Bangalore,13.054202,77.674002,41.6
9,Owner,0,1,2,BHK,879.120879,1,1,Chennai,12.951610,80.140970,36.0

In [4]:
 data.isnull().sum()

POSTED_BY                0
UNDER_CONSTRUCTION       0
RERA                     0
BHK_NO.                  0
BHK_OR_RK                0
SQUARE_FT                0
READY_TO_MOVE            0
RESALE                   0
City                     9
LONGITUDE                0
LATITUDE                 0
TARGET(PRICE_IN_LACS)    0
dtype: int64

In [5]:
data["City"].fillna(11,inplace=True)

In [6]:
data.isnull().sum()

POSTED_BY                0
UNDER_CONSTRUCTION       0
RERA                     0
BHK_NO.                  0
BHK_OR_RK                0
SQUARE_FT                0
READY_TO_MOVE            0
RESALE                   0
City                     0
LONGITUDE                0
LATITUDE                 0
TARGET(PRICE_IN_LACS)    0
dtype: int64

# Q1. Find the owner & dealar whose target price below 60 lack but they should approval by RERA?

In [9]:
a=data.loc[((data["POSTED_BY"]=="Owner")|(data["POSTED_BY"]=="Dealer"))&(data["RERA"]==1)&(data["TARGET(PRICE_IN_LACS)"]<=60)]
a

,POSTED_BY,UNDER_CONSTRUCTION,RERA,BHK_NO.,BHK_OR_RK,SQUARE_FT,READY_TO_MOVE,RESALE,City,LONGITUDE,LATITUDE,TARGET(PRICE_IN_LACS)
7,Owner,0,1,3,BHK,1181.012946,1,1,Mohali,30.740000,76.650000,52.0
8,Dealer,0,1,2,BHK,1040.000000,1,1,Bangalore,13.054202,77.674002,41.6
9,Owner,0,1,2,BHK,879.120879,1,1,Chennai,12.951610,80.140970,36.0
22,Dealer,0,1,3,BHK,1310.147689,1,1,Noida,28.504100,77.381557,55.0
31,Dealer,0,1,2,BHK,943.126608,1,1,Noida,28.504100,77.381557,33.0
...,...,...,...,...,...,...,...,...,...,...,...,...
29404,Dealer,0,1,2,BHK,942.269409,1,1,Bangalore,12.860000,77.786000,28.4
29407,Owner,0,1,3,BHK,1463.679075,1,1,Vadodara,22.271214,73.188827,40.5
29416,Owner,0,1,1,BHK,550.055005,1,1,Meerut,28.939024,77.689176,10.0
29417,Dealer,1,1,2,BHK,656.628376,0,1,Pune,18.582300,73.983000,42.3
29450,Dealer,0,1,2,BHK,896.774194,1,1,Jaipur,26.832353,75.841749,27.8

In [11]:
a["POSTED_BY"].unique()

array(['Owner', 'Dealer'], dtype=object)

In [12]:
a["RERA"].unique()

array([1], dtype=int64)

In [16]:
b=a["TARGET(PRICE_IN_LACS)"].unique()
b

array([52.  , 41.6 , 36.  , 55.  , 33.  , 51.6 , 39.9 , 22.1 , 60.  ,
       24.9 , 42.  , 50.  , 48.  , 38.  , 46.  , 11.  , 57.9 , 33.9 ,
       30.  , 21.5 , 45.9 , 58.5 , 50.2 , 44.9 , 37.5 , 40.  , 23.  ,
       49.  , 40.6 , 36.1 , 46.6 , 45.  , 43.  , 51.  , 26.3 , 48.9 ,
       16.  , 19.1 , 37.  , 35.  , 55.5 , 49.6 , 29.5 , 48.4 , 23.5 ,
       41.  , 33.7 , 59.5 , 33.5 , 44.  , 48.1 , 54.9 , 22.5 , 31.7 ,
       30.6 , 32.  , 47.  , 53.  , 23.4 , 21.9 , 21.8 , 49.8 , 47.3 ,
       23.9 , 41.5 , 26.5 , 17.3 , 47.2 , 58.  , 30.5 , 54.  , 20.  ,
       34.  , 20.6 , 24.5 , 48.5 , 57.4 , 56.  , 34.5 , 36.5 , 54.5 ,
       29.  , 41.8 , 47.7 , 35.9 , 27.  , 57.  , 56.9 , 18.  , 46.9 ,
       29.8 , 43.2 , 47.1 , 25.  , 26.  , 55.4 , 39.  , 54.7 , 18.5 ,
       55.9 , 29.3 , 44.7 , 25.4 , 20.9 , 32.5 , 42.9 , 28.  , 56.6 ,
       21.4 , 41.9 , 48.3 , 13.1 , 23.1 , 32.8 , 10.5 , 31.1 , 58.7 ,
       46.8 , 12.9 , 19.3 , 11.9 , 15.9 , 38.2 , 59.  , 53.4 , 32.9 ,
       29.4 , 12.5 , 31.5 , 52.5 , 46.7 , 59.2 , 44.3 , 42.1 , 49.5 ,
       51.9 , 30.7 , 24.1 , 52.6 , 22.9 , 49.7 , 23.2 , 55.1 , 32.1 ,
       52.8 , 29.9 , 34.8 , 26.2 , 30.4 , 46.4 , 27.5 , 43.3 , 44.8 ,
       27.2 , 28.5 , 19.6 , 32.7 , 59.1 , 31.  , 35.2 , 31.9 , 53.7 ,
       38.1 , 56.4 , 45.6 , 13.2 , 55.3 , 25.8 , 53.2 , 22.  , 59.8 ,
       56.5 , 29.1 , 22.6 , 34.9 , 32.2 , 24.8 , 28.2 , 25.2 , 39.1 ,
       46.5 , 38.5 , 46.1 , 35.5 , 39.8 ,  8.5 , 18.6 , 25.5 , 16.7 ,
       24.  , 54.3 , 51.2 , 31.4 , 45.5 , 26.1 , 58.4 , 57.1 , 12.  ,
       46.3 , 44.5 , 30.2 , 24.7 , 18.7 , 15.1 , 54.6 , 21.3 , 47.6 ,
       42.4 , 17.5 , 14.  , 42.3 , 47.5 , 52.7 , 28.6 , 57.5 , 41.1 ,
       30.8 ,  8.  , 57.3 , 41.7 , 37.2 , 59.9 , 37.7 , 20.1 , 55.8 ,
       20.5 , 19.5 , 48.6 , 40.3 , 12.6 , 35.3 , 27.9 , 40.5 , 15.3 ,
       28.9 , 16.9 , 43.7 , 44.6 , 37.8 , 36.4 , 33.11, 34.7 , 53.9 ,
       45.4 , 43.5 , 18.2 , 49.9 , 19.  , 29.6 , 17.  , 48.8 , 43.1 ,
       23.7 , 40.1 , 51.5 , 50.66, 15.  , 34.2 , 56.7 , 21.  , 31.6 ,
       32.6 , 33.6 , 58.8 , 39.5 , 30.1 , 24.2 , 50.6 , 23.8 , 16.5 ,
       40.2 , 55.6 , 38.3 , 43.6 , 42.8 , 59.7 , 36.8 , 40.4 , 42.5 ,
       37.3 , 42.2 , 39.4 , 13.  , 50.4 , 38.8 , 25.9 , 19.7 , 25.7 ,
        1.  , 39.6 , 16.6 , 50.5 , 56.3 , 27.6 , 11.2 , 37.1 , 28.1 ,
       56.2 , 22.8 , 14.5 , 39.7 , 20.7 , 52.9 , 52.1 , 58.6 , 55.2 ,
       31.3 , 13.9 , 50.7 , 29.2 , 40.9 , 52.3 , 58.1 , 26.4 , 45.1 ,
       41.2 , 54.1 , 43.9 , 48.7 ,  6.5 , 57.7 , 33.2 , 15.5 , 22.2 ,
       50.8 , 31.2 , 46.2 , 58.2 , 57.6 , 35.1 , 24.4 , 34.1 , 38.79,
       33.3 , 54.2 , 40.8 , 56.8 , 25.6 , 49.2 , 34.3 , 26.7 , 26.9 ,
       36.9 , 15.6 , 52.4 , 20.3 , 34.6 , 39.2 , 37.9 , 19.9 , 23.3 ,
       43.8 , 38.7 , 49.3 , 26.6 , 49.1 , 30.9 , 44.1 , 11.6 , 53.5 ,
       51.8 , 13.6 , 53.3 , 59.3 , 57.8 , 47.9 , 14.9 , 27.3 , 44.87,
       43.4 , 14.3 , 38.9 , 39.3 , 13.5 , 36.7 , 19.2 , 20.4 , 27.7 ,
       27.4 ,  9.  , 35.7 , 25.1 , 18.4 , 54.8 , 15.4 , 44.4 , 25.3 ,
       23.6 , 48.2 , 12.4 , 18.9 ,  4.5 , 44.2 ,  9.5 , 28.8 , 51.3 ,
       28.7 , 36.2 , 58.9 , 36.6 , 52.2 , 47.8 ,  9.3 , 45.8 , 32.4 ,
       10.  , 38.4 , 55.7 ,  7.5 , 41.4 , 15.8 , 25.11, 35.85, 14.4 ,
       14.8 , 50.9 , 37.4 , 59.6 , 18.1 , 17.6 , 24.3 , 56.1 ,  9.1 ,
       40.7 , 41.3 , 17.8 , 17.9 , 42.7 , 20.8 , 20.2 , 28.3 , 21.2 ,
       33.1 , 35.8 , 47.4 , 34.4 , 16.3 , 50.1 , 51.1 , 37.6 , 35.6 ,
       32.3 , 13.8 , 22.3 , 36.3 , 42.6 , 45.2 , 10.9 , 59.4 ,  1.5 ,
       21.6 ,  8.1 , 57.2 , 18.3 , 28.4 , 27.8 ])

In [19]:
a["TARGET(PRICE_IN_LACS)"].value_counts()

60.00    107
55.00     95
45.00     95
50.00     75
35.00     72
        ...
44.87      1
57.80      1
35.30      1
10.50      1
27.80      1
Name: TARGET(PRICE_IN_LACS), Length: 456, dtype: int64

In [27]:
len(b)

456

# Q2. Find 2BHK Owners but target price 60-90 and that should be ready to move?

In [41]:
d=data.loc[(((data["TARGET(PRICE_IN_LACS)"]>=60)&(data["TARGET(PRICE_IN_LACS)"]<=90)))&(data["POSTED_BY"]=="Owner")&(data["BHK_NO."]==2)&(data["READY_TO_MOVE"]==1)]

In [42]:
d

,POSTED_BY,UNDER_CONSTRUCTION,RERA,BHK_NO.,BHK_OR_RK,SQUARE_FT,READY_TO_MOVE,RESALE,City,LONGITUDE,LATITUDE,TARGET(PRICE_IN_LACS)
3,Owner,0,1,2,BHK,929.921143,1,1,Ghaziabad,28.642300,77.344500,62.5
13,Owner,0,1,2,BHK,1122.171946,1,1,Noida,28.587711,77.403123,62.0
56,Owner,0,0,2,BHK,950.014616,1,1,Aurangabad,19.888790,75.343440,65.0
68,Owner,0,0,2,BHK,5000.000000,1,1,Jaipur,26.850391,75.814198,85.0
71,Owner,0,0,2,BHK,760.070940,1,1,Belgaum,15.866670,74.500000,60.0
...,...,...,...,...,...,...,...,...,...,...,...,...
29274,Owner,0,1,2,BHK,1300.014445,1,1,Bangalore,12.969910,77.597960,90.0
29310,Owner,0,0,2,BHK,1345.390384,1,1,Ghaziabad,28.709030,77.495662,61.0
29338,Owner,0,0,2,BHK,1216.022890,1,1,Jaipur,26.850391,75.814198,85.0
29359,Owner,0,0,2,BHK,1423.324151,1,1,Bangalore,12.911464,77.604916,62.0
29449,Owner,0,0,2,BHK,927.079009,1,1,Chennai,12.900150,80.227910,67.0

# Q3. Find the Owners whose flat under counstruction  but these flat approve by RERA and show target price ?

In [43]:
e=data.loc[(data["POSTED_BY"]=="Owner")&(data["UNDER_CONSTRUCTION"]==1)&(data["RERA"]==1)]
e

,POSTED_BY,UNDER_CONSTRUCTION,RERA,BHK_NO.,BHK_OR_RK,SQUARE_FT,READY_TO_MOVE,RESALE,City,LONGITUDE,LATITUDE,TARGET(PRICE_IN_LACS)
100,Owner,1,1,2,BHK,989.902989,0,1,Noida,28.503500,77.426447,50.0
122,Owner,1,1,2,BHK,1109.165207,0,1,Udupi,13.278237,74.747328,38.0
161,Owner,1,1,4,BHK,2700.075602,0,1,Noida,28.535689,77.359671,250.0
684,Owner,1,1,2,BHK,1069.937370,0,1,Mohali,30.650000,76.820000,41.0
888,Owner,1,1,3,BHK,1575.000000,0,1,Chandigarh,30.662283,76.822397,69.3
...,...,...,...,...,...,...,...,...,...,...,...,...
29202,Owner,1,1,2,BHK,877.425044,0,1,Faridabad,28.380160,77.369936,19.9
29322,Owner,1,1,2,BHK,990.099010,0,1,Noida,28.503500,77.426447,46.0
29326,Owner,1,1,2,BHK,1114.126553,0,1,Bangalore,13.031800,77.658300,78.0
29360,Owner,1,1,2,BHK,1090.159104,0,1,Lucknow,26.748868,80.863332,37.0
29436,Owner,1,1,2,BHK,1175.132676,0,1,Bangalore,12.995893,77.761394,62.0

In [44]:
e["POSTED_BY"].unique()

array(['Owner'], dtype=object)

In [46]:
e["UNDER_CONSTRUCTION"].unique()

array([1], dtype=int64)

In [47]:
e["RERA"].unique()

array([1], dtype=int64)

# Q4. Find Owners and dealers those flat size below 900 square foot and increase the target price by 5 lack?

In [48]:
data

,POSTED_BY,UNDER_CONSTRUCTION,RERA,BHK_NO.,BHK_OR_RK,SQUARE_FT,READY_TO_MOVE,RESALE,City,LONGITUDE,LATITUDE,TARGET(PRICE_IN_LACS)
0,Owner,0,0,2,BHK,1300.236407,1,1,Bangalore,12.969910,77.597960,55.0
1,Dealer,0,0,2,BHK,1275.000000,1,1,Mysore,12.274538,76.644605,51.0
2,Owner,0,0,2,BHK,933.159722,1,1,Bangalore,12.778033,77.632191,43.0
3,Owner,0,1,2,BHK,929.921143,1,1,Ghaziabad,28.642300,77.344500,62.5
4,Dealer,1,0,2,BHK,999.009247,0,1,Kolkata,22.592200,88.484911,60.5
...,...,...,...,...,...,...,...,...,...,...,...,...
29446,Owner,0,0,3,BHK,2500.000000,1,1,Agra,27.140626,78.043277,45.0
29447,Owner,0,0,2,BHK,769.230769,1,1,Lake View Recidency,39.945409,-86.150721,16.0
29448,Dealer,0,0,2,BHK,1022.641509,1,1,Jaipur,26.928785,75.828002,27.1
29449,Owner,0,0,2,BHK,927.079009,1,1,Chennai,12.900150,80.227910,67.0
29450,Dealer,0,1,2,BHK,896.774194,1,1,Jaipur,26.832353,75.841749,27.8

In [49]:
f=data.loc[(data["POSTED_BY"]!="Builder")&(data["SQUARE_FT"]<=900)]
f

,POSTED_BY,UNDER_CONSTRUCTION,RERA,BHK_NO.,BHK_OR_RK,SQUARE_FT,READY_TO_MOVE,RESALE,City,LONGITUDE,LATITUDE,TARGET(PRICE_IN_LACS)
9,Owner,0,1,2,BHK,879.120879,1,1,Chennai,12.951610,80.140970,36.0
14,Owner,0,0,1,BHK,649.983750,1,1,Raigad,13.035200,77.577200,20.0
20,Owner,0,0,2,BHK,881.143529,1,1,Chennai,13.050000,80.110000,45.0
23,Dealer,0,0,1,BHK,630.000630,1,1,Mumbai,19.054440,72.840560,300.0
25,Owner,0,0,2,BHK,780.141844,1,1,Kolkata,22.541110,88.337780,27.5
...,...,...,...,...,...,...,...,...,...,...,...,...
29431,Owner,0,0,2,BHK,712.105799,1,1,Kolkata,22.541110,88.337780,21.0
29437,Dealer,0,0,2,BHK,760.116253,1,1,Kolkata,22.541110,88.337780,34.0
29444,Dealer,1,1,1,BHK,752.049334,0,1,Mumbai,19.175900,72.952200,100.0
29447,Owner,0,0,2,BHK,769.230769,1,1,Lake View Recidency,39.945409,-86.150721,16.0
29450,Dealer,0,1,2,BHK,896.774194,1,1,Jaipur,26.832353,75.841749,27.8

In [50]:
h=f["TARGET(PRICE_IN_LACS)"]+5
h

9         41.0
14        25.0
20        50.0
23       305.0
25        32.5
         ...
29431     26.0
29437     39.0
29444    105.0
29447     21.0
29450     32.8
Name: TARGET(PRICE_IN_LACS), Length: 7086, dtype: float64

In [51]:
f["NewTarget"]=h

C:\Users\DELL\AppData\Local\Temp\ipykernel_10364\1388481910.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  f["NewTarget"]=h

In [52]:
f

,POSTED_BY,UNDER_CONSTRUCTION,RERA,BHK_NO.,BHK_OR_RK,SQUARE_FT,READY_TO_MOVE,RESALE,City,LONGITUDE,LATITUDE,TARGET(PRICE_IN_LACS),NewTarget
9,Owner,0,1,2,BHK,879.120879,1,1,Chennai,12.951610,80.140970,36.0,41.0
14,Owner,0,0,1,BHK,649.983750,1,1,Raigad,13.035200,77.577200,20.0,25.0
20,Owner,0,0,2,BHK,881.143529,1,1,Chennai,13.050000,80.110000,45.0,50.0
23,Dealer,0,0,1,BHK,630.000630,1,1,Mumbai,19.054440,72.840560,300.0,305.0
25,Owner,0,0,2,BHK,780.141844,1,1,Kolkata,22.541110,88.337780,27.5,32.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...
29431,Owner,0,0,2,BHK,712.105799,1,1,Kolkata,22.541110,88.337780,21.0,26.0
29437,Dealer,0,0,2,BHK,760.116253,1,1,Kolkata,22.541110,88.337780,34.0,39.0
29444,Dealer,1,1,1,BHK,752.049334,0,1,Mumbai,19.175900,72.952200,100.0,105.0
29447,Owner,0,0,2,BHK,769.230769,1,1,Lake View Recidency,39.945409,-86.150721,16.0,21.0
29450,Dealer,0,1,2,BHK,896.774194,1,1,Jaipur,26.832353,75.841749,27.8,32.8

# Q5. Find dealers those are having RERA approved and that flat size 2 BHK then decrease price by 2 lakh & above 2 BHK the increase price by 7 lakh ?

### For  2 BHK decrease 2 in target price

In [87]:
j=data.loc[(data["POSTED_BY"]=="Dealer")&(data["RERA"]==1)&(data["BHK_NO."]==2)]
j

,POSTED_BY,UNDER_CONSTRUCTION,RERA,BHK_NO.,BHK_OR_RK,SQUARE_FT,READY_TO_MOVE,RESALE,City,LONGITUDE,LATITUDE,TARGET(PRICE_IN_LACS)
8,Dealer,0,1,2,BHK,1040.000000,1,1,Bangalore,13.054202,77.674002,41.6
31,Dealer,0,1,2,BHK,943.126608,1,1,Noida,28.504100,77.381557,33.0
34,Dealer,0,1,2,BHK,857.786197,1,0,Maharashtra,19.175900,72.952200,240.0
36,Dealer,1,1,2,BHK,1020.087884,0,1,Pune,18.599300,73.762500,65.0
41,Dealer,0,1,2,BHK,1058.114928,1,1,Pune,18.539812,73.737678,65.0
...,...,...,...,...,...,...,...,...,...,...,...,...
29402,Dealer,0,1,2,BHK,1015.977770,1,0,Bangalore,12.550000,77.417000,58.5
29404,Dealer,0,1,2,BHK,942.269409,1,1,Bangalore,12.860000,77.786000,28.4
29417,Dealer,1,1,2,BHK,656.628376,0,1,Pune,18.582300,73.983000,42.3
29439,Dealer,1,1,2,BHK,975.609756,0,1,Lalitpur,22.281215,70.789479,120.0
29450,Dealer,0,1,2,BHK,896.774194,1,1,Jaipur,26.832353,75.841749,27.8

In [96]:
price2=[]
for x in j["TARGET(PRICE_IN_LACS)"]:
        k=x-2
        price2.append(k)
print(price2)

[39.6, 31.0, 238.0, 63.0, 63.0, 49.6, 68.0, 20.1, 79.5, 22.9, 40.0, 58.4, 46.0, 62.900000000000006, 44.0, 328.0, 178.0, 31.9, 108.0, 88.0, 138.0, 148.0, 138.0, 68.0, 19.5, 108.0, 43.9, 44.0, 118.0, 42.9, 158.0, 48.0, 63.5, 108.0, 89.0, 388.0, 368.0, 98.0, 38.6, 83.0, 34.1, 43.0, 41.0, 188.0, 49.0, 76.5, 74.5, 64.4, 148.0, 98.0, 228.0, 95.0, 68.0, 158.0, 128.0, 28.0, 76.0, 47.0, 53.5, 76.0, 44.0, 27.5, 46.4, 21.5, 128.0, 39.0, 98.0, 58.0, 298.0, 31.700000000000003, 66.4, 178.0, 118.0, 42.0, 46.1, 108.0, 63.0, 53.0, 20.5, 178.0, 29.7, 62.5, 38.0, 128.0, 50.0, 63.0, 72.5, 45.0, 118.0, 79.3, 63.0, 19.9, 98.0, 108.0, 58.0, 35.0, 19.8, 45.3, 21.9, 39.5, 93.0, 41.0, 47.0, 128.0, 108.0, 88.0, 79.0, 22.9, 88.0, 89.0, 56.0, 47.0, 52.0, 248.0, 18.6, 22.5, 54.0, 61.0, 73.0, 32.5, 60.0, 98.0, 52.5, 27.0, 148.0, 148.0, 31.0, 268.0, 39.8, 47.0, 45.7, 108.0, 138.0, 33.9, 168.0, 228.0, 41.0, 298.0, 76.0, 98.0, 158.0, 93.0, 56.0, 27.8, 128.0, 41.2, 108.0, 97.0, 45.1, 46.9, 108.0, 448.0, 158.0, 75.9, 52.7, 128.0, 6698.0, 61.1, 148.0, 42.7, 23.4, 158.0, 45.1, 44.0, 64.0, 26.0, 78.3, 108.0, 52.0, 19.4, 70.9, 39.9, 98.0, 158.0, 5068.0, 85.0, 148.0, 238.0, 31.0, 118.0, 148.0, 83.0, 318.0, 98.0, 51.0, 138.0, 30.799999999999997, 29.1, 54.0, 51.0, 87.0, 44.8, 17.3, 338.0, 58.0, 55.0, 34.1, 39.0, 188.0, 13.9, 79.3, 81.0, 108.0, 98.0, 31.0, 83.0, 47.0, 138.0, 43.0, 118.0, 158.0, 55.0, 88.0, 63.0, 52.0, 30.0, 158.0, 178.0, 72.8, 36.2, 89.9, 56.0, 57.0, 51.4, 83.0, 30.9, 9.9, 58.0, 59.0, 27.4, 108.0, 61.2, 278.0, 328.0, 128.0, 58.3, 23.0, 49.0, 158.0, 63.0, 53.4, 61.0, 40.1, 52.0, 47.5, 248.0, 188.0, 74.0, 118.0, 51.4, 53.0, 148.0, 49.9, 42.3, 138.0, 47.0, 22.1, 178.0, 74.0, 158.0, 86.0, 68.0, 67.0, 20.9, 47.7, 138.0, 148.0, 77.0, 21.2, 71.0, 85.0, 168.0, 168.0, 29.5, 118.0, 44.0, 148.0, 58.3, 78.0, 77.0, 30.1, 32.0, 21.0, 51.0, 69.2, 79.0, 89.0, 208.0, 73.0, 27.0, 108.0, 44.4, 79.0, 27.9, 16.5, 78.0, 25.5, 36.0, 42.8, 77.0, 98.0, 17.6, 348.0, 30.700000000000003, 78.0, 31.0, 29.0, 66.0, 158.0, 55.0, 77.2, 29.9, 51.7, 93.0, 23.0, 128.0, 63.0, 81.0, 138.0, 36.1, 78.0, 298.0, 138.0, 90.0, 93.5, 84.0, 54.4, 85.0, 69.5, 62.0, 168.0, 43.6, 25.0, 148.0, 89.3, 25.0, 13.9, 58.0, 86.0, 43.9, 198.0, 138.0, 23.8, 81.7, 76.0, 63.0, 45.0, 248.0, 238.0, 428.0, 26.0, 63.0, 188.0, 64.0, 51.0, 51.2, 57.8, 138.0, 36.0, 54.5, 30.5, 138.0, 27.1, 178.0, 20.6, 45.0, 248.0, 228.0, 81.0, 62.0, 98.0, 32.9, 218.0, 41.0, 41.0, 30.200000000000003, 118.0, 118.0, 22.8, 26.2, 37.1, 13.9, 93.0, 168.0, 44.1, 54.0, 62.0, 138.0, 33.5, 68.0, 448.0, 178.0, 90.0, 54.0, 78.0, 70.5, 98.0, 138.0, 98.0, 86.1, 71.0, 64.0, 91.0, 128.0, 34.0, 65.0, 58.0, 61.8, 45.7, 68.6, 23.5, 31.700000000000003, 66.0, 76.0, 22.9, 24.0, 46.1, 92.7, 9598.0, 94.0, 158.0, 81.0, 49.2, 58.0, 68.2, 29.4, 43.5, 24.1, 77.9, 56.4, 76.0, 18.0, 288.0, 288.0, 98.0, 66.0, 43.0, 18.6, 64.9, 76.0, 108.0, 76.0, 34.0, 68.0, 178.0, 44.3, 42.5, 188.0, 22.7, 32.9, 70.0, 13.1, 44.4, 52.0, 19.9, 148.0, 89.0, 178.0, 78.0, 20.0, 66.0, 148.0, 63.0, 44.0, 31.700000000000003, 65.1, 83.0, 58.0, 96.0, 45.6, 138.0, 80.0, 158.0, 248.0, 158.0, 91.5, 98.0, 88.0, 168.0, 258.0, 37.9, 128.0, 55.0, 178.0, 29.0, 44.8, 178.0, 96.5, 23.0, 138.0, 75.0, 178.0, 36.0, 168.0, 228.0, 61.8, 70.0, 41.3, 29.0, 158.0, 93.0, 98.0, 32.9, 108.0, 97.0, 9538.0, 59.0, 138.0, 49.9, 67.0, 68.0, 43.0, 50.0, 138.0, 21.0, 208.0, 95.9, 35.2, 91.8, 51.0, 208.0, 18.1, 34.0, 258.0, 98.0, 87.5, 98.0, 73.0, 30.0, 43.0, 168.0, 80.0, 128.0, 17.5, 73.0, 168.0, 46.6, 33.0, 38.3, 23.5, 68.0, 538.0, 188.0, 33.3, 73.0, 34.0, 278.0, 248.0, 77.6, 61.0, 148.0, 158.0, 87.0, 158.0, 77.1, 25.9, 188.0, 98.0, 45.0, 368.0, 46.0, 38.0, 218.0, 258.0, 45.0, 13.3, 96.0, 288.0, 82.0, 88.0, 26.9, 29.5, 248.0, 61.0, 67.0, 248.0, 26.0, 74.0, 45.7, 52.5, 198.0, 41.7, 298.0, 47.0, 40.9, 64.0, 98.0, 178.0, 42.6, 108.0, 158.0, 49.0, 168.0, 83.0, 22.0, 38.0, 90.2, 158.0, 25.9, 63.0, 63.0, 40.1, 76.0, 80.0, 68.0, 51.0, 198.0, 118.0, 178.0, 40.0, 118.0, 93.0, 158.0, 70.0, 43.4, 98.0, 158.0, 98.0, 59.0, 138.0, 278.0, 228.0, 41.5, 44.5, 76.0, 73.0, 288.0, 92.0, 9988.0, 77.0, 29.0, 61.0, 118.0, 37.0, 16.2, 40.0, 79.0, 15.5, 95.0, 30.0, 27.1, 148.0, 158.0, 83.0, 47.0, 82.5, 66.5, 198.0, 208.0, 138.0, 70.0, 75.9, 36.2, 108.0, 46.8, 218.0, 93.0, 188.0, 108.0, 41.1, 118.0, 90.5, 108.0, 43.0, 77.0, 93.0, 45.0, 81.8, 31.0, 70.0, 25.0, 108.0, 49.5, 258.0, 83.0, 248.0, 168.0, 44.0, 178.0, 118.0, 52.9, 148.0, 138.0, 268.0, 108.0, 80.2, 66.5, 50.0, 43.0, 76.0, 82.3, 53.3, 178.0, 328.0, 52.5, 31.700000000000003, 40.0, 148.0, 298.0, 24.0, 25.5, 168.0, 29.9, 9448.0, 59.1, 70.0, 49.0, 63.5, 9198.0, 29.6, 30.6, 70.7, 80.0, 58.0, 108.0, 57.0, 56.8, 138.0, 168.0, 70.0, 30.5, 118.0, 59.9, 188.0, 178.0, 238.0, 45.5, 138.0, 318.0, 138.0, 83.0, 28.1, 66.2, 48.0, 158.0, 88.9, 158.0, 22.2, 148.0, 55.0, 158.0, 43.0, 208.0, 48.6, 22.0, 148.0, 76.0, 25.5, 83.0, 28.1, 70.9, 61.0, 248.0, 19.5, 38.2, 188.0, 74.2, 53.0, 148.0, 148.0, 97.0, 34.0, 138.0, 54.9, 118.0, 65.0, 83.0, 53.0, 60.0, 218.0, 398.0, 75.0, 14.899999999999999, 46.6, 9628.0, 308.0, 45.7, 148.0, 35.7, 208.0, 55.4, 50.0, 97.0, 148.0, 128.0, 128.0, 21.5, 98.0, 31.0, 98.0, 41.6, 80.4, 33.0, 158.0, 55.0, 34.0, 81.7, 65.3, 32.0, 61.0, 58.5, 148.0, 90.0, 73.0, 67.9, 148.0, 54.5, 81.3, 108.0, 34.8, 52.3, 38.4, 79.0, 25.5, 83.5, 66.0, 52.0, 40.5, 68.0, 35.3, 138.0, 138.0, 26.6, 40.2, 38.3, 70.0, 46.0, 74.0, 148.0, 73.0, 98.0, 47.0, 248.0, 38.0, 98.0, 48.4, 36.8, 64.0, 138.0, 138.0, 158.0, 19.4, 8798.0, 17.5, 64.0, 118.0, 17.7, 118.0, 56.5, 428.0, 108.0, 138.0, 98.0, 108.0, 128.0, 178.0, 74.0, 36.0, 188.0, 43.0, 148.0, 98.0, 41.0, 70.0, 14.600000000000001, 48.5, 23.7, 178.0, 28.0, 97.0, 158.0, 79.9, 45.7, 358.0, 54.3, 278.0, 53.0, 93.5, 48.0, 38.0, 92.5, 168.0, 8998.0, 68.5, 108.0, 64.0, 208.0, 83.0, 60.0, 128.0, 25.6, 44.0, 56.0, 34.0, 98.0, 178.0, 89.9, 85.0, 23.0, 23.4, 228.0, 20.0, 30.0, 128.0, 77.0, 42.9, 188.0, 7358.0, 58.0, 69.0, 80.0, 58.0, 87.1, 25.0, 97.0, 258.0, 98.0, 44.9, 80.0, 20.8, 238.0, 41.5, 238.0, 85.5, 65.1, 98.0, 148.0, 18.0, 118.0, 178.0, 9238.0, 41.1, 128.0, 41.5, 4588.0, 40.9, 158.0, 49.2, 82.0, 90.0, 58.0, 66.7, 47.0, 98.0, 158.0, 74.0, 62.0, 50.1, 148.0, 41.7, 55.0, 46.3, 58.0, 61.2, 60.0, 188.0, 31.700000000000003, 78.0, 168.0, 21.9, 53.2, 79.0, 92.0, 258.0, 93.0, 93.0, 88.0, 128.0, 138.0, 188.0, 138.0, 48.5, 118.0, 45.0, 108.0, 98.0, 108.0, 58.0, 69.0, 29.0, 34.0, 60.6, 31.0, 77.0, 70.0, 42.7, 118.0, 68.0, 85.0, 48.7, 87.0, 7298.0, 36.8, 15.5, 128.0, 53.5, 37.5, 50.0, 69.0, 98.0, 43.0, 76.0, 9848.0, 94.0, 138.0, 39.0, 30.0, 48.0, 258.0, 108.0, 97.0, 60.5, 61.0, 50.3, 77.0, 63.0, 56.1, 52.6, 138.0, 198.0, 158.0, 80.0, 118.0, 23.8, 41.0, 75.0, 94.0, 68.0, 52.5, 56.0, 68.8, 108.0, 158.0, 63.0, 36.2, 128.0, 45.2, 108.0, 43.0, 53.0, 53.3, 72.5, 158.0, 148.0, 168.0, 86.7, 54.0, 108.0, 41.5, 56.0, 9198.0, 108.0, 218.0, 66.7, 88.0, 93.0, 19.0, 29.0, 89.0, 208.0, 56.0, 22.0, 41.9, 48.0, 46.7, 63.0, 89.0, 47.9, 67.0, 95.0, 158.0, 138.0, 20.8, 66.0, 158.0, 138.0, 51.0, 42.9, 37.0, 48.4, 53.0, 40.0, 228.0, 64.0, 78.0, 168.0, 34.0, 49.0, 9148.0, 29.0, 68.0, 46.1, 94.0, 65.0, 58.0, 21.0, 358.0, 378.0, 118.0, 20.9, 25.0, 88.0, 57.0, 228.0, 69.0, 148.0, 168.0, 53.1, 128.0, 228.0, 178.0, 54.0, 54.0, 7978.0, 20.2, 32.0, 45.5, 118.0, 34.0, 108.0, 128.0, 98.0, 188.0, 36.8, 80.0, 95.0, 56.2, 30.0, 55.6, 57.0, 65.9, 45.3, 108.0, 9018.0, 45.0, 128.0, 89.0, 22.4, 31.0, 50.5, 87.0, 368.0, 46.5, 21.0, 32.1, 108.0, 168.0, 178.0, 40.0, 148.0, 24.3, 118.0, 26.0, 40.0, 83.0, 98.0, 43.0, 90.3, 118.0, 30.0, 128.0, 50.8, 78.0, 118.0, 148.0, 17.6, 138.0, 98.0, 29.7, 118.0, 50.1, 61.0, 88.0, 108.0, 108.0, 128.0, 63.400000000000006, 52.3, 49.0, 41.5, 148.0, 108.0, 278.0, 108.0, 80.0, 21.0, 39.9, 138.0, 98.0, 57.1, 108.0, 118.0, 108.0, 118.0, 30.0, 358.0, 45.0, 46.1, 188.0, 37.0, 338.0, 21.0, 92.0, 73.9, 20.6, 98.0, 86.0, 81.0, 64.0, 83.0, 158.0, 188.0, 58.0, 138.0, 98.0, 38.8, 158.0, 55.0, 52.2, 178.0, 53.9, 36.0, 60.0, 54.0, 98.0, 30.0, 108.0, 31.6, 54.8, 22.5, 158.0, 63.0, 37.9, 23.6, 41.3, 158.0, 60.0, 89.5, 51.0, 58.0, 53.5, 21.8, 35.0, 49.0, 138.0, 138.0, 47.2, 98.0, 43.9, 36.5, 31.0, 65.0, 35.0, 37.7, 43.4, 63.0, 138.0, 51.0, 40.5, 76.7, 21.5, 54.0, 33.9, 98.0, 38.5, 318.0, 198.0, 65.0, 198.0, 168.0, 39.0, 24.7, 138.0, 168.0, 42.9, 58.0, 148.0, 80.0, 44.0, 60.0, 108.0, 52.0, 118.0, 118.0, 7898.0, 52.2, 31.700000000000003, 35.5, 34.9, 74.0, 248.0, 56.5, 28.0, 30.6, 148.0, 58.7, 56.0, 21.5, 52.9, 59.3, 198.0, 87.0, 79.0, 138.0, 18.9, 69.5, 44.4, 168.0, 68.0, 98.0, 53.0, 98.0, 46.0, 66.0, 42.9, 50.4, 138.0, 61.6, 74.0, 29.0, 74.7, 158.0, 93.0, 84.0, 158.0, 53.0, 148.0, 58.0, 44.0, 138.0, 108.0, 90.0, 31.0, 18.6, 31.9, 34.0, 42.0, 86.0, 198.0, 42.0, 17.9, 53.0, 73.0, 98.0, 36.0, 108.0, 148.0, 80.0, 21.3, 9598.0, 85.0, 98.0, 52.7, 118.0, 198.0, 68.0, 77.0, 60.0, 42.6, 63.5, 50.1, 92.0, 218.0, 46.4, 49.0, 41.8, 67.0, 118.0, 46.0, 28.5, 108.0, 158.0, 72.0, 56.0, 79.0, 228.0, 53.0, 34.0, 46.7, 148.0, 24.9, 40.0, 36.7, 70.0, 108.0, 47.3, 53.0, 138.0, 98.0, 74.0, 53.3, 51.0, 35.3, 19.5, 75.0, 138.0, 59.0, 198.0, 50.9, 74.0, 238.0, 118.0, 47.0, 66.0, 158.0, 148.0, 128.0, 42.3, 228.0, 46.0, 75.0, 85.0, 67.0, 158.0, 60.0, 24.6, 48.0, 7798.0, 80.0, 308.0, 73.0, 52.1, 89.6, 43.9, 31.0, 188.0, 28.9, 38.0, 62.5, 53.0, 50.9, 31.9, 94.0, 148.0, 35.5, 64.5, 73.0, 51.0, 50.0, 108.0, 108.0, 62.400000000000006, 118.0, 138.0, 56.1, 77.0, 22.0, 28.5, 73.0, 25.0, 42.0, 64.0, 36.7, 168.0, 39.0, 148.0, 37.6, 58.0, 158.0, 118.0, 32.0, 148.0, 69.1, 31.299999999999997, 148.0, 67.6, 148.0, 22.2, 42.9, 82.9, 178.0, 8798.0, 37.7, 25.9, 66.0, 138.0, 55.7, 258.0, 118.0, 82.9, 25.5, 54.6, 108.0, 68.0, 218.0, 128.0, 21.0, 11.6, 98.0, 38.0, 53.0, 30.0, 348.0, 118.0, 78.0, 34.0, 24.9, 158.0, 158.0, 148.0, 138.0, 298.0, 97.0, 23.0, 58.2, 71.9, 128.0, 36.0, 78.0, 33.0, 158.0, 228.0, 30.0, 48.2, 54.6, 31.6, 47.7, 86.9, 38.0, 68.0, 33.5, 128.0, 168.0, 57.0, 56.6, 22.5, 298.0, 36.0, 23.8, 228.0, 33.5, 148.0, 73.0, 58.0, 14.0, 248.0, 93.0, 48.4, 198.0, 108.0, 168.0, 118.0, 52.0, 388.0, 158.0, 47.5, 46.0, 38.8, 98.0, 44.0, 12.9, 66.0, 76.5, 97.0, 45.5, 14.5, 9.0, 74.0, 38.5, 24.0, 67.0, 158.0, 63.0, 33.0, 33.0, 42.87, 31.9, 87.0, 98.0, 39.9, 75.0, 258.0, 41.4, 108.0, 35.3, 33.0, 64.0, 44.6, 58.0, 36.0, 61.0, 168.0, 39.9, 26.1, 53.3, 31.9, 76.0, 57.0, 45.0, 328.0, 40.4, 168.0, 49.8, 158.0, 29.7, 36.9, 98.0, 168.0, 21.3, 118.0, 73.0, 37.3, 128.0, 27.5, 248.0, 63.0, 72.0, 43.0, 70.0, 138.0, 79.0, 25.9, 98.0, 34.0, 94.0, 178.0, 34.9, 138.0, 72.0, 65.0, 68.6, 55.0, 39.5, 64.9, 148.0, 56.0, 108.0, 148.0, 108.0, 48.6, 108.0, 228.0, 28.8, 21.5, 54.0, 128.0, 32.2, 248.0, 21.9, 98.0, 34.0, 28.0, 49.5, 128.0, 37.7, 16.2, 46.6, 72.0, 118.0, 36.9, 18.4, 36.0, 128.0, 42.8, 18.5, 168.0, 25.3, 138.0, 39.0, 49.9, 258.0, 158.0, 14.899999999999999, 35.0, 25.4, 65.0, 44.5, 68.0, 108.0, 61.0, 108.0, 65.0, 30.6, 138.0, 31.0, 36.2, 81.0, 57.5, 158.0, 268.0, 50.9, 90.0, 63.0, 178.0, 128.0, 54.0, 18.4, 82.4, 22.4, 76.5, 30.0, 258.0, 158.0, 98.0, 98.0, 178.0, 35.8, 138.0, 46.5, 47.0, 67.0, 82.0, 108.0, 35.7, 188.0, 148.0, 40.5, 76.0, 7978.0, 178.0, 318.0, 62.0, 108.0, 388.0, 118.0, 22.9, 128.0, 68.0, 60.0, 93.0, 128.0, 26.5, 108.0, 188.0, 91.0, 338.0, 17.1, 63.0, 85.0, 148.0, 81.0, 76.0, 128.0, 42.5, 43.0, 69.7, 61.0, 158.0, 49.8, 43.0, 50.9, 11.0, 31.6, 108.0, 178.0, 138.0, 63.0, 47.5, 59.0, 28.0, 31.9, 73.0, 64.0, 118.0, 168.0, 70.0, 74.0, 168.0, 48.0, 45.0, 168.0, 61.0, 82.8, 59.0, 63.0, 42.6, 47.3, 23.1, 92.0, 90.1, 95.0, 45.0, 108.0, 35.9, 148.0, 44.2, 148.0, 44.0, 34.5, 148.0, 72.4, 35.0, 74.0, 23.1, 168.0, 128.0, 128.0, 88.0, 79.0, 81.4, 38.3, 168.0, 118.0, 56.0, 93.0, 4658.0, 288.0, 40.0, 228.0, 21.3, 85.8, 34.5, 168.0, 41.1, 79.0, 80.2, 97.0, 138.0, 188.0, 148.0, 98.0, 63.0, 41.0, 29.0, 35.8, 308.0, 54.4, 78.0, 28.6, 138.0, 148.0, 37.0, 308.0, 77.0, 108.0, 23.2, 98.0, 40.2, 35.1, 178.0, 98.0, 17.9, 28.1, 43.0, 57.0, 84.0, 80.0, 22.1, 98.0, 61.0, 54.8, 17.5, 128.0, 51.0, 228.0, 47.9, 148.0, 298.0, 188.0, 28.6, 238.0, 59.5, 71.8, 62.0, 168.0, 178.0, 128.0, 34.1, 138.0, 158.0, 208.0, 208.0, 22.0, 73.6, 41.5, 42.4, 61.8, 158.0, 128.0, 108.0, 108.0, 70.0, 358.0, 96.0, 108.0, 46.1, 70.0, 53.0, 70.5, 42.3, 58.0, 95.0, 158.0, 41.1, 40.0, 98.0, 208.0, 308.0, 26.0, 40.0, 128.0, 98.0, 108.0, 188.0, 108.0, 128.0, 148.0, 68.0, 23.9, 228.0, 108.0, 118.0, 83.0, 50.3, 59.9, 56.0, 42.0, 73.0, 118.0, 98.0, 21.8, 88.0, 86.0, 94.0, 33.1, 42.2, 198.0, 82.0, 108.0, 18.1, 87.0, 21.5, 55.4, 32.5, 258.0, 74.7, 37.5, 258.0, 108.0, 31.0, 198.0, 53.0, 79.0, 22.0, 218.0, 97.0, 66.4, 49.3, 49.5, 62.8, 25.0, 9698.0, 238.0, 44.3, 108.0, 36.0, 26.7, 40.0, 31.0, 7298.0, 158.0, 34.8, 128.0, 248.0, 148.0, 98.0, 148.0, 108.0, 24.0, 34.2, 21.5, 93.0, 63.0, 208.0, 41.9, 34.5, 9198.0, 138.0, 62.0, 98.0, 60.0, 48.0, 178.0, 90.0, 66.5, 89.9, 218.0, 72.0, 148.0, 178.0, 43.6, 128.0, 9498.0, 44.9, 60.4, 98.0, 62.8, 68.0, 22.7, 96.7, 98.0, 98.0, 2588.0, 61.9, 53.4, 34.5, 138.0, 98.0, 40.0, 22.1, 57.7, 75.5, 118.0, 168.0, 65.0, 45.8, 62.5, 82.4, 30.0, 55.0, 36.0, 138.0, 168.0, 168.0, 148.0, 42.0, 108.0, 178.0, 218.0, 52.0, 54.0, 248.0, 42.0, 12.9, 30.4, 98.0, 15.5, 77.8, 27.2, 70.0, 92.8, 49.0, 33.0, 50.0, 42.7, 238.0, 71.8, 82.0, 56.5, 66.0, 60.0, 56.0, 198.0, 158.0, 41.0, 128.0, 118.0, 33.9, 36.5, 37.5, 72.5, 97.0, 108.0, 39.4, 93.0, 13.8, 78.0, 23.11, 39.0, 56.5, 33.85, 51.0, 24.0, 82.9, 118.0, 138.0, 45.2, 118.0, 90.2, 268.0, 62.0, 43.0, 208.0, 24.3, 138.0, 45.9, 71.0, 75.1, 47.0, 42.5, 178.0, 9.0, 45.5, 208.0, 158.0, 74.9, 22.9, 27.9, 45.0, 90.4, 248.0, 138.0, 168.0, 118.0, 53.1, 51.9, 52.0, 22.9, 58.0, 128.0, 118.0, 83.0, 218.0, 358.0, 37.2, 38.0, 67.9, 70.0, 17.7, 178.0, 35.5, 128.0, 36.0, 76.0, 148.0, 90.4, 39.5, 59.5, 53.4, 228.0, 178.0, 75.1, 60.0, 67.6, 34.7, 52.0, 69.0, 59.0, 83.5, 358.0, 14.0, 28.5, 88.0, 40.0, 73.9, 238.0, 35.3, 148.0, 35.9, 88.0, 14.899999999999999, 368.0, 54.7, 138.0, 218.0, 62.0, 98.0, 98.0, 73.0, 178.0, 34.0, 98.0, 33.0, 65.2, 88.0, 37.4, 50.4, 73.0, 76.0, 19.0, 118.0, 108.0, 128.0, 54.0, 6668.0, 78.7, 53.0, 98.0, 38.3, 41.9, 77.9, 84.5, 96.0, 258.0, 35.4, 128.0, 97.0, 67.5, 27.8, 128.0, 27.0, 32.2, 198.0, 82.0, 68.5, 51.5, 57.0, 47.0, 61.0, 51.5, 108.0, 81.6, 42.0, 68.0, 27.0, 46.9, 32.1, 88.0, 228.0, 45.5, 19.3, 78.0, 118.0, 67.0, 148.0, 128.0, 98.0, 42.5, 72.5, 33.0, 68.0, 50.0, 81.0, 86.0, 208.0, 43.6, 24.0, 168.0, 76.6, 13.9, 50.0, 128.0, 53.9, 94.0, 67.7, 90.0, 98.0, 118.0, 65.0, 218.0, 22.3, 218.0, 138.0, 58.0, 83.0, 108.0, 69.6, 71.0, 43.1, 148.0, 64.0, 32.5, 25.0, 98.0, 66.1, 96.0, 58.0, 85.0, 65.0, 388.0, 58.0, 52.9, 98.0, 118.0, 27.9, 50.8, 68.9, 49.0, 9148.0, 60.4, 93.1, 90.1, 81.0, 108.0, 108.0, 46.0, 27.5, 24.0, 118.0, 21.1, 178.0, 63.0, 66.0, 47.8, 138.0, 48.0, 50.6, 148.0, 38.7, 118.0, 178.0, 17.9, 65.0, 79.0, 128.0, 38.0, 108.0, 29.0, 51.2, 73.0, 198.0, 98.0, 198.0, 98.0, 35.0, 45.8, 28.0, 74.6, 89.0, 27.0, 128.0, 98.0, 35.5, 64.0, 72.0, 128.0, 47.9, 58.0, 57.9, 44.0, 42.9, 43.9, 57.0, 32.5, 23.6, 88.0, 128.0, 40.0, 26.5, 97.0, 82.0, 57.5, 178.0, 38.0, 188.0, 53.0, 63.0, 108.0, 27.4, 158.0, 39.4, 85.0, 45.7, 55.5, 26.0, 158.0, 158.0, 75.0, 21.5, 74.0, 62.3, 318.0, 44.0, 128.0, 178.0, 7858.0, 21.2, 55.0, 22.5, 21.2, 40.4, 118.0, 80.5, 138.0, 79.6, 42.7, 158.0, 40.0, 54.5, 138.0, 17.5, 268.0, 228.0, 158.0, 64.0, 90.0, 97.0, 188.0, 36.0, 128.0, 36.8, 59.4, 21.3, 85.5, 98.0, 138.0, 98.0, 71.6, 148.0, 98.0, 63.0, 53.4, 77.0, 88.0, 138.0, 28.5, 66.0, 208.0, 66.1, 98.0, 27.5, 27.0, 28.0, 158.0, 168.0, 41.7, 158.0, 108.0, 93.0, 28.9, 70.0, 118.0, 108.0, 188.0, 148.0, 66.0, 118.0, 18.2, 79.0, 128.0, 218.0, 71.8, 228.0, 65.0, 43.0, 108.0, 68.5, 59.0, 45.1, 61.3, 118.0, 98.0, 98.0, 78.0, 98.0, 138.0, 69.0, 92.0, 228.0, 26.3, 158.0, 56.0, 28.0, 86.4, 58.0, 158.0, 53.0, 98.0, 47.9, 178.0, 148.0, 138.0, 58.0, 39.9, 26.9, 46.0, 158.0, 148.0, 248.0, 178.0, 148.0, 21.8, 118.0, 88.0, 66.5, 168.0, 9588.0, 86.0, 30.1, 38.0, 128.0, 178.0, 69.0, 27.6, 63.7, 68.9, 258.0, 80.8, 22.9, 52.0, 40.9, 23.5, 35.0, 36.0, 128.0, 98.0, 33.0, 50.1, 50.9, 39.7, 208.0, 26.0, 118.0, 91.0, 138.0, 128.0, 62.0, 45.0, 75.0, 42.0, 62.099999999999994, 14.5, 60.0, 128.0, 64.0, 108.0, 62.5, 41.2, 148.0, 83.0, 108.0, 48.0, 56.4, 208.0, 31.1, 42.9, 30.6, 57.0, 37.9, 40.0, 21.8, 118.0, 158.0, 88.0, 20.0, 65.0, 148.0, 158.0, 42.7, 33.5, 44.0, 63.0, 118.0, 47.8, 168.0, 118.0, 45.0, 158.0, 22.9, 198.0, 118.0, 27.4, 31.299999999999997, 57.0, 69.9, 158.0, 348.0, 98.0, 98.0, 39.0, 158.0, 26.7, 35.5, 48.0, 98.0, 26.8, 87.7, 62.3, 408.0, 9018.0, 61.0, 60.7, 98.0, 82.0, 98.0, 35.5, 148.0, 76.0, 44.5, 338.0, 63.0, 128.0, 75.0, 25.9, 38.0, 58.0, 21.1, 108.0, 42.0, 57.0, 41.0, 228.0, 228.0, 45.4, 158.0, 42.0, 108.0, 168.0, 27.0, 198.0, 178.0, 188.0, 43.9, 46.0, 98.0, 32.4, 40.7, 228.0, 75.0, 108.0, 95.8, 128.0, 49.2, 32.1, 89.0, 118.0, 94.0, 79.0, 168.0, 36.5, 98.0, 72.9, 44.8, 108.0, 118.0, 41.3, 148.0, 118.0, 158.0, 44.7, 128.0, 73.0, 79.1, 178.0, 83.0, 76.0, 39.0, 25.0, 128.0, 28.6, 67.0, 80.0, 28.0, 258.0, 46.8, 35.6, 69.0, 18.5, 54.9, 36.0, 37.0, 53.0, 78.0, 84.0, 47.0, 24.2, 77.0, 57.3, 36.0, 35.6, 28.0, 52.7, 258.0, 69.9, 15.0, 138.0, 98.0, 108.0, 31.0, 35.9, 128.0, 56.5, 69.0, 40.5, 45.4, 158.0, 41.0, 138.0, 58.0, 70.0, 81.0, 168.0, 9198.0, 75.0, 148.0, 118.0, 358.0, 338.0, 108.0, 75.0, 26.5, 50.0, 56.0, 72.0, 138.0, 33.6, 39.5, 30.299999999999997, 338.0, 178.0, 54.0, 21.0, 128.0, 53.6, 138.0, 138.0, 78.3, 72.8, 61.0, 238.0, 23.2, 108.0, 19.5, 49.0, 58.0, 51.0, 46.1, 87.0, 43.8, 218.0, 93.0, 29.2, 30.5, 54.9, 49.2, 39.6, 188.0, 69.9, 74.0, 378.0, 98.0, 66.0, 168.0, 98.0, 68.6, 32.0, 218.0, 35.2, 55.7, 208.0, 178.0, 47.9, 93.0, 83.0, 34.5, 41.0, 288.0, 98.0, 63.0, 63.599999999999994, 70.5, 98.0, 34.0, 69.4, 41.0, 47.9, 48.0, 118.0, 62.5, 57.5, 22.0, 66.0, 43.5, 30.0, 59.6, 8998.0, 8888.0, 228.0, 20.3, 178.0, 96.0, 398.0, 68.0, 34.0, 33.5, 21.2, 83.0, 47.9, 78.3, 178.0, 40.6, 108.0, 128.0, 57.0, 43.0, 21.9, 48.0, 98.0, 258.0, 17.0, 44.2, 43.2, 58.0, 88.0, 148.0, 158.0, 378.0, 83.0, 72.0, 45.8, 168.0, 78.0, 86.7, 188.0, 27.5, 228.0, 50.8, 31.1, 46.0, 8.9, 95.0, 41.4, 128.0, 69.9, 30.200000000000003, 78.0, 108.0, 22.5, 60.0, 36.0, 32.9, 108.0, 83.0, 31.0, 67.5, 118.0, 31.299999999999997, 23.5, 80.0, 9628.0, 52.2, 36.0, 208.0, 88.9, 72.0, 108.0, 34.5, 41.6, 61.0, 108.0, 168.0, 348.0, 48.0, 118.0, 21.2, 108.0, 218.0, 79.3, 38.0, 56.0, 67.5, 14.5, 81.0, 33.9, 84.0, 108.0, 21.9, 70.0, 20.8, 258.0, 63.0, 43.4, 8808.0, 83.0, 118.0, 198.0, 35.0, 138.0, 70.0, 108.0, 51.0, 41.0, 39.9, 55.6, 97.0, 44.5, 168.0, 37.3, 59.0, 198.0, 39.9, 98.0, 66.0, 138.0, 36.7, 148.0, 66.0, 53.0, 44.0, 408.0, 168.0, 19.6, 92.6, 63.0, 41.7, 49.0, 77.0, 85.5, 39.0, 93.0, 21.0, 35.0, 89.0, 52.2, 74.8, 78.0, 43.0, 58.0, 54.0, 108.0, 31.0, 118.0, 98.0, 49.0, 148.0, 98.0, 98.0, 53.0, 40.6, 168.0, 138.0, 57.0, 85.0, 75.0, 58.2, 51.7, 58.0, 33.0, 46.8, 40.0, 28.0, 108.0, 128.0, 71.5, 65.2, 37.5, 77.0, 56.2, 83.0, 48.9, 73.0, 398.0, 108.0, 56.0, 88.0, 158.0, 25.0, 26.2, 33.9, 158.0, 36.5, 60.0, 58.0, 188.0, 93.0, 158.0, 66.9, 21.5, 78.3, 53.0, 85.6, 70.0, 65.5, 65.0, 218.0, 138.0, 53.0, 23.9, 43.0, 37.1, 148.0, 67.4, 388.0, 158.0, 73.3, 78.0, 23.9, 53.1, 32.9, 43.8, 138.0, 288.0, 24.0, 178.0, 35.3, 178.0, 148.0, 258.0, 30.5, 65.6, 128.0, 28.6, 25.0, 27.9, 9148.0, 148.0, 45.1, 208.0, 26.5, 138.0, 52.0, 29.0, 31.200000000000003, 79.0, 18.1, 69.0, 74.8, 67.0, 41.0, 98.0, 98.0, 33.9, 468.0, 22.0, 23.9, 24.3, 23.9, 43.5, 138.0, 58.9, 74.5, 78.0, 40.0, 97.0, 56.0, 188.0, 30.1, 93.0, 93.0, 54.2, 258.0, 70.0, 218.0, 84.0, 108.0, 54.0, 56.5, 26.4, 40.3, 118.0, 25.8]

In [ ]:
j.insert(11,"NT",price2)

In [91]:
j

,POSTED_BY,UNDER_CONSTRUCTION,RERA,BHK_NO.,BHK_OR_RK,SQUARE_FT,READY_TO_MOVE,RESALE,City,LONGITUDE,LATITUDE,NT,TARGET(PRICE_IN_LACS)
8,Dealer,0,1,2,BHK,1040.000000,1,1,Bangalore,13.054202,77.674002,39.6,41.6
31,Dealer,0,1,2,BHK,943.126608,1,1,Noida,28.504100,77.381557,31.0,33.0
34,Dealer,0,1,2,BHK,857.786197,1,0,Maharashtra,19.175900,72.952200,238.0,240.0
36,Dealer,1,1,2,BHK,1020.087884,0,1,Pune,18.599300,73.762500,63.0,65.0
41,Dealer,0,1,2,BHK,1058.114928,1,1,Pune,18.539812,73.737678,63.0,65.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
29402,Dealer,0,1,2,BHK,1015.977770,1,0,Bangalore,12.550000,77.417000,56.5,58.5
29404,Dealer,0,1,2,BHK,942.269409,1,1,Bangalore,12.860000,77.786000,26.4,28.4
29417,Dealer,1,1,2,BHK,656.628376,0,1,Pune,18.582300,73.983000,40.3,42.3
29439,Dealer,1,1,2,BHK,975.609756,0,1,Lalitpur,22.281215,70.789479,118.0,120.0
29450,Dealer,0,1,2,BHK,896.774194,1,1,Jaipur,26.832353,75.841749,25.8,27.8

## for above 2 BHK Increase 7 in Target price

In [92]:
l=data.loc[(data["POSTED_BY"]=="Dealer")&(data["RERA"]==1)&(data["BHK_NO."]>2)]
l

,POSTED_BY,UNDER_CONSTRUCTION,RERA,BHK_NO.,BHK_OR_RK,SQUARE_FT,READY_TO_MOVE,RESALE,City,LONGITUDE,LATITUDE,TARGET(PRICE_IN_LACS)
15,Dealer,1,1,3,BHK,1394.117647,0,1,Noida,28.429614,77.481711,71.1
17,Dealer,1,1,3,BHK,2124.896706,0,1,Bangalore,12.885500,77.563800,180.0
19,Dealer,0,1,3,BHK,2178.649237,1,1,Bangalore,13.092356,77.613468,120.0
22,Dealer,0,1,3,BHK,1310.147689,1,1,Noida,28.504100,77.381557,55.0
43,Dealer,0,1,3,BHK,1274.924779,1,1,Mumbai,22.803593,83.755013,250.0
...,...,...,...,...,...,...,...,...,...,...,...,...
29386,Dealer,0,1,3,BHK,1727.115717,1,1,Bangalore,12.984700,77.549100,140.0
29399,Dealer,0,1,3,BHK,1850.149391,1,1,Ghaziabad,28.919600,76.897200,80.5
29409,Dealer,0,1,4,BHK,5399.568035,1,1,Surat,21.143354,72.770931,400.0
29435,Dealer,0,1,4,BHK,2189.160468,1,1,Chandigarh,30.662283,76.822397,82.4
29443,Dealer,0,1,3,BHK,1161.194975,1,1,Maharashtra,19.111438,72.878724,220.0

In [93]:
l["BHK_NO."].unique()

array([3, 4, 5, 6], dtype=int64)

In [98]:
price7=[]
for x in l["TARGET(PRICE_IN_LACS)"]:
    m=x+7
    price7.append(m)
print(price7)

[78.1, 187.0, 127.0, 62.0, 257.0, 78.9, 287.0, 217.0, 787.0, 107.0, 447.0, 147.0, 477.0, 247.0, 107.0, 307.0, 64.9, 106.0, 257.0, 117.0, 287.0, 86.5, 117.0, 167.0, 86.0, 407.0, 167.0, 107.0, 307.0, 227.0, 55.0, 57.2, 117.0, 187.0, 69.9, 44.5, 106.0, 177.0, 167.0, 477.0, 1207.0, 53.6, 357.0, 327.0, 74.0, 33.3, 177.0, 177.0, 757.0, 167.0, 70.0, 117.0, 257.0, 257.0, 307.0, 117.0, 85.0, 127.0, 42.0, 187.0, 94.0, 101.0, 247.0, 7287.0, 227.0, 104.6, 167.0, 79.0, 377.0, 117.0, 137.0, 207.0, 70.8, 1197.0, 357.0, 187.0, 90.0, 64.9, 77.0, 677.0, 66.5, 127.0, 107.0, 277.0, 61.9, 58.0, 94.5, 197.0, 187.0, 477.0, 37.6, 106.0, 100.0, 147.0, 397.0, 127.0, 60.0, 70.9, 127.0, 79.0, 147.0, 227.0, 557.0, 127.0, 56.8, 137.0, 72.2, 117.0, 54.2, 377.0, 107.0, 79.0, 102.9, 167.0, 67.0, 437.0, 9157.0, 55.5, 64.4, 147.0, 107.0, 76.0, 247.0, 54.3, 73.0, 207.0, 72.0, 47.0, 88.0, 187.0, 287.0, 51.0, 90.9, 104.6, 5167.0, 70.9, 237.0, 127.0, 83.1, 82.0, 317.0, 207.0, 107.0, 137.0, 53.9, 207.0, 107.0, 177.0, 52.0, 147.0, 187.0, 647.0, 147.0, 137.0, 367.0, 947.0, 217.0, 137.0, 137.0, 107.0, 54.2, 327.0, 76.5, 187.0, 62.4, 102.0, 127.0, 76.5, 81.0, 75.0, 62.9, 36.3, 81.0, 507.0, 81.9, 67.0, 69.9, 82.6, 49.9, 137.0, 83.1, 217.0, 105.0, 537.0, 227.0, 157.0, 127.0, 137.0, 83.0, 95.9, 50.0, 107.0, 187.0, 187.0, 65.7, 327.0, 65.0, 117.0, 100.0, 95.0, 147.0, 177.0, 88.9, 117.0, 467.0, 287.0, 137.0, 117.0, 507.0, 507.0, 45.0, 267.0, 107.0, 33.5, 157.0, 177.0, 33.3, 117.0, 127.0, 84.2, 68.4, 92.0, 127.0, 157.0, 747.0, 56.0, 75.0, 137.0, 1107.0, 59.0, 157.0, 79.2, 72.0, 137.0, 74.6, 107.0, 48.0, 277.0, 137.0, 77.0, 83.8, 297.0, 107.0, 257.0, 217.0, 377.0, 117.0, 357.0, 167.0, 91.7, 90.0, 9327.0, 65.0, 53.7, 127.0, 72.0, 66.2, 247.0, 51.3, 247.0, 43.5, 63.0, 107.0, 42.0, 96.9, 87.0, 137.0, 517.0, 137.0, 117.0, 65.5, 59.6, 55.5, 167.0, 177.0, 1157.0, 72.0, 89.0, 157.0, 92.0, 127.0, 103.5, 247.0, 62.1, 197.0, 117.0, 59.8, 267.0, 297.0, 81.5, 97.0, 147.0, 102.0, 59.0, 97.0, 33.2, 78.2, 107.0, 207.0, 337.0, 257.0, 137.0, 167.0, 187.0, 257.0, 100.0, 277.0, 74.5, 197.0, 90.5, 547.0, 137.0, 73.0, 137.0, 82.5, 34.2, 247.0, 197.0, 92.7, 177.0, 87.0, 317.0, 107.0, 127.0, 107.0, 41.5, 197.0, 197.0, 81.0, 197.0, 527.0, 6467.0, 94.4, 56.6, 93.4, 52.0, 217.0, 247.0, 41.5, 59.0, 41.0, 7837.0, 907.0, 61.0, 1607.0, 177.0, 287.0, 55.0, 71.1, 327.0, 107.0, 407.0, 197.0, 87.0, 117.0, 327.0, 257.0, 127.0, 1057.0, 91.9, 127.0, 277.0, 48.0, 197.0, 257.0, 187.0, 1157.0, 43.0, 207.0, 187.0, 157.0, 87.0, 127.0, 217.0, 257.0, 68.5, 64.0, 537.0, 70.3, 72.0, 317.0, 87.0, 85.5, 257.0, 86.8, 117.0, 102.0, 1117.0, 103.0, 157.0, 117.0, 207.0, 137.0, 157.0, 83.9, 967.0, 177.0, 287.0, 127.0, 197.0, 137.0, 507.0, 59.5, 87.2, 32.2, 32.0, 337.0, 277.0, 217.0, 51.0, 187.0, 53.5, 197.0, 187.0, 68.0, 71.9, 357.0, 46.8, 267.0, 247.0, 64.0, 91.1, 82.0, 117.0, 54.0, 207.0, 347.0, 137.0, 62.0, 217.0, 105.0, 76.0, 63.5, 167.0, 247.0, 38.5, 287.0, 86.5, 137.0, 177.0, 147.0, 187.0, 577.0, 69.7, 287.0, 457.0, 73.8, 187.0, 177.0, 237.0, 137.0, 707.0, 297.0, 217.0, 287.0, 137.0, 197.0, 92.0, 177.0, 137.0, 61.3, 487.0, 66.5, 137.0, 39.5, 357.0, 74.9, 137.0, 9547.0, 447.0, 91.7, 76.5, 69.0, 74.1, 307.0, 117.0, 217.0, 367.0, 177.0, 197.0, 247.0, 105.0, 547.0, 102.0, 267.0, 267.0, 66.0, 527.0, 137.0, 85.6, 75.7, 507.0, 61.6, 197.0, 127.0, 39.8, 227.0, 657.0, 107.0, 1207.0, 84.5, 7447.0, 107.0, 177.0, 267.0, 617.0, 107.0, 367.0, 41.0, 24.5, 73.5, 397.0, 83.9, 167.0, 127.0, 72.0, 257.0, 127.0, 54.5, 687.0, 327.0, 59.7, 147.0, 237.0, 35.6, 64.5, 9767.0, 277.0, 68.7, 217.0, 117.0, 36.5, 48.1, 167.0, 267.0, 277.0, 277.0, 77.5, 57.0, 177.0, 257.0, 72.0, 247.0, 7837.0, 98.8, 97.0, 237.0, 267.0, 127.0, 347.0, 64.0, 85.0, 187.0, 357.0, 197.0, 417.0, 68.3, 1007.0, 107.0, 107.0, 98.0, 287.0, 287.0, 247.0, 107.0, 74.0, 71.0, 66.9, 287.0, 147.0, 57.0, 107.0, 103.0, 9437.0, 60.0, 187.0, 147.0, 217.0, 117.0, 77.0, 78.6, 97.0, 49.0, 87.5, 337.0, 137.0, 62.8, 82.0, 1107.0, 137.0, 147.0, 82.0, 237.0, 117.0, 137.0, 72.0, 117.0, 63.0, 307.0, 102.0, 527.0, 107.0, 327.0, 96.0, 287.0, 237.0, 107.0, 52.0, 70.9, 79.6, 72.1, 707.0, 75.2, 78.5, 227.0, 127.0, 87.6, 187.0, 1187.0, 187.0, 70.0, 227.0, 237.0, 587.0, 95.0, 277.0, 67.6, 167.0, 177.0, 73.2, 227.0, 63.0, 73.0, 56.5, 317.0, 68.0, 1357.0, 104.0, 227.0, 66.9, 117.0, 147.0, 347.0, 74.0, 307.0, 88.0, 207.0, 52.0, 267.0, 36.0, 327.0, 44.8, 77.1, 74.0, 47.5, 61.0, 367.0, 107.0, 327.0, 84.0, 177.0, 137.0, 197.0, 92.0, 61.3, 43.4, 85.0, 107.0, 257.0, 40.11, 117.0, 217.0, 41.7, 66.8, 74.0, 72.9, 74.1, 977.0, 36.5, 72.2, 417.0, 207.0, 207.0, 78.0, 83.0, 207.0, 32.8, 217.0, 83.8, 92.0, 59.0, 577.0, 317.0, 97.0, 117.0, 65.0, 60.0, 81.0, 102.7, 107.0, 32.4, 96.0, 197.0, 87.5, 117.0, 127.0, 84.9, 637.0, 357.0, 97.0, 78.6, 377.0, 137.0, 117.0, 167.0, 59.5, 127.0, 147.0, 177.0, 117.0, 58.6, 83.4, 347.0, 807.0, 227.0, 457.0, 257.0, 47.0, 407.0, 97.0, 127.0, 327.0, 117.0, 687.0, 207.0, 77.0, 74.0, 51.9, 87.0, 30.7, 157.0, 47.1, 107.0, 9207.0, 337.0, 267.0, 337.0, 117.0, 197.0, 157.0, 71.6, 767.0, 207.0, 277.0, 137.0, 107.0, 86.1, 157.0, 107.0, 9507.0, 117.0, 137.0, 9207.0, 247.0, 55.0, 99.0, 81.5, 70.5, 83.9, 53.0, 76.6, 387.0, 197.0, 217.0, 59.0, 337.0, 307.0, 57.66, 247.0, 407.0, 1097.0, 73.9, 4007.0, 68.8, 127.0, 137.0, 101.0, 68.8, 147.0, 41.2, 9537.0, 80.9, 71.0, 107.0, 417.0, 807.0, 94.0, 367.0, 147.0, 127.0, 187.0, 77.4, 63.7, 103.0, 91.9, 72.4, 83.1, 187.0, 227.0, 33.2, 53.0, 64.9, 167.0, 197.0, 127.0, 97.8, 187.0, 617.0, 187.0, 88.0, 40.6, 337.0, 49.0, 98.3, 687.0, 46.8, 58.2, 54.2, 577.0, 82.0, 92.5, 81.0, 127.0, 177.0, 44.0, 447.0, 177.0, 65.8, 84.9, 72.0, 227.0, 177.0, 77.9, 187.0, 117.0, 107.0, 237.0, 52.9, 117.0, 217.0, 717.0, 437.0, 197.0, 117.0, 87.1, 66.0, 117.0, 357.0, 117.0, 677.0, 347.0, 93.0, 247.0, 90.6, 277.0, 117.0, 327.0, 137.0, 62.6, 147.0, 52.0, 60.0, 127.0, 127.0, 257.0, 50.7, 117.0, 237.0, 57.0, 105.0, 50.0, 77.0, 75.0, 77.4, 85.0, 127.0, 63.0, 34.0, 247.0, 337.0, 107.0, 197.0, 277.0, 97.0, 39.7, 68.0, 33.3, 217.0, 217.0, 52.0, 107.0, 88.2, 74.6, 137.0, 137.0, 327.0, 59.8, 147.0, 177.0, 102.0, 217.0, 63.7, 417.0, 38.0, 30.9, 82.4, 107.0, 207.0, 147.0, 127.0, 49.8, 66.7, 137.0, 97.0, 86.9, 87.0, 257.0, 41.5, 107.0, 437.0, 167.0, 39.0, 91.2, 90.9, 103.0, 907.0, 187.0, 447.0, 54.0, 46.4, 58.0, 277.0, 81.3, 80.0, 127.0, 137.0, 82.0, 147.0, 117.0, 207.0, 127.0, 66.0, 38.4, 88.0, 80.0, 427.0, 157.0, 89.0, 317.0, 57.0, 98.6, 93.6, 93.5, 9457.0, 47.5, 387.0, 117.0, 38.9, 53.0, 257.0, 75.0, 127.0, 30.0, 85.0, 137.0, 327.0, 237.0, 187.0, 72.0, 187.0, 177.0, 82.2, 88.9, 117.0, 227.0, 68.0, 117.0, 32.7, 337.0, 807.0, 167.0, 147.0, 137.0, 100.7, 104.0, 62.0, 69.0, 60.2, 77.0, 167.0, 287.0, 107.0, 1097.0, 177.0, 61.0, 117.0, 197.0, 75.0, 63.3, 137.0, 83.9, 117.0, 417.0, 53.4, 627.0, 78.5, 102.0, 54.0, 197.0, 44.0, 42.9, 105.0, 7407.0, 62.0, 217.0, 73.8, 217.0, 80.0, 44.1, 84.6, 257.0, 35.1, 217.0, 287.0, 157.0, 63.2, 317.0, 91.5, 197.0, 127.0, 88.8, 227.0, 257.0, 507.0, 207.0, 82.0, 91.9, 127.0, 50.0, 67.3, 85.0, 347.0, 67.9, 127.0, 227.0, 63.9, 197.0, 76.9, 68.5, 167.0, 95.3, 307.0, 277.0, 237.0, 94.0, 177.0, 197.0, 137.0, 97.5, 307.0, 79.7, 83.0, 52.9, 97.0, 72.8, 59.9, 84.0, 237.0, 63.5, 317.0, 65.6, 307.0, 83.3, 157.0, 347.0, 267.0, 82.0, 69.0, 237.0, 187.0, 117.0, 237.0, 76.0, 967.0, 657.0, 62.9, 237.0, 93.6, 177.0, 107.0, 67.0, 84.9, 90.6, 93.9, 95.0, 82.2, 117.0, 127.0, 117.0, 107.0, 93.9, 207.0, 237.0, 187.0, 109.0, 217.0, 307.0, 857.0, 277.0, 92.0, 92.0, 51.9, 117.0, 277.0, 187.0, 127.0, 69.9, 157.0, 207.0, 64.0, 207.0, 89.0, 62.0, 107.0, 127.0, 427.0, 387.0, 84.7, 67.0, 96.3, 227.0, 83.9, 64.9, 207.0, 137.0, 107.0, 83.5, 68.8, 66.9, 267.0, 437.0, 75.2, 84.0, 207.0, 103.0, 107.0, 72.0, 147.0, 106.4, 78.7, 69.0, 247.0, 137.0, 8687.0, 107.0, 107.0, 106.5, 147.0, 86.2, 105.0, 277.0, 377.0, 217.0, 81.5, 107.0, 287.0, 347.0, 52.1, 507.0, 167.0, 107.0, 427.0, 187.0, 117.0, 417.0, 75.0, 79.0, 357.0, 117.0, 137.0, 49.8, 157.0, 83.8, 69.6, 237.0, 197.0, 247.0, 8407.0, 347.0, 82.0, 237.0, 48.2, 207.0, 127.0, 74.9, 117.0, 167.0, 287.0, 86.9, 227.0, 97.0, 61.1, 9017.0, 207.0, 167.0, 77.8, 327.0, 66.5, 49.5, 86.0, 106.0, 33.3, 187.0, 127.0, 90.8, 367.0, 71.2, 177.0, 100.6, 127.0, 677.0, 167.0, 92.7, 54.5, 117.0, 317.0, 64.0, 157.0, 107.0, 197.0, 317.0, 64.1, 34.5, 90.9, 37.0, 59.5, 75.0, 79.0, 79.4, 59.0, 127.0, 9917.0, 64.7, 147.0, 137.0, 187.0, 207.0, 287.0, 117.0, 77.0, 197.0, 58.2, 73.9, 101.0, 59.1, 52.0, 54.3, 187.0, 427.0, 157.0, 39.5, 277.0, 1807.0, 337.0, 51.0, 127.0, 92.0, 207.0, 187.0, 78.5, 157.0, 567.0, 177.0, 77.0, 41.0, 63.3, 197.0, 46.9, 80.0, 177.0, 33.2, 237.0, 117.0, 117.0, 33.2, 57.8, 227.0, 337.0, 38.2, 237.0, 117.0, 257.0, 517.0, 53.2, 177.0, 58.2, 597.0, 117.0, 117.0, 117.0, 2007.0, 42.1, 46.0, 137.0, 98.5, 79.7, 50.0, 207.0, 277.0, 74.0, 217.0, 52.9, 45.79, 99.0, 8407.0, 147.0, 217.0, 327.0, 237.0, 437.0, 52.5, 40.3, 88.0, 72.0, 107.0, 83.9, 107.0, 75.9, 377.0, 91.9, 32.9, 127.0, 327.0, 227.0, 49.2, 167.0, 137.0, 74.5, 137.0, 277.0, 54.5, 227.0, 87.0, 107.0, 627.0, 85.0, 66.0, 77.0, 57.0, 237.0, 117.0, 327.0, 107.0, 147.0, 147.0, 33.1, 207.0, 187.0, 827.0, 105.4, 217.0, 247.0, 61.0, 101.0, 69.8, 117.0, 87.0, 127.0, 107.0, 61.2, 79.0, 63.0, 197.0, 87.0, 197.0, 72.9, 59.0, 87.0, 437.0, 157.0, 103.0, 73.5, 87.0, 197.0, 237.0, 147.0, 99.0, 237.0, 137.0, 8907.0, 187.0, 227.0, 96.9, 42.0, 76.3, 137.0, 61.9, 99.0, 41.7, 69.9, 97.0, 82.2, 257.0, 277.0, 237.0, 507.0, 69.5, 85.0, 127.0, 100.0, 76.64, 44.2, 94.5, 177.0, 69.4, 207.0, 1107.0, 807.0, 49.2, 217.0, 207.0, 427.0, 397.0, 80.0, 367.0, 84.5, 187.0, 147.0, 127.0, 71.5, 54.0, 227.0, 107.0, 79.8, 377.0, 59.0, 88.0, 94.0, 91.5, 147.0, 167.0, 63.9, 81.0, 137.0, 86.2, 157.0, 147.0, 76.5, 137.0, 247.0, 60.9, 367.0, 7397.0, 177.0, 507.0, 147.0, 257.0, 257.0, 26.0, 167.0, 2107.0, 52.1, 75.0, 367.0, 127.0, 69.0, 137.0, 82.0, 49.5, 147.0, 287.0, 106.0, 29.8, 56.0, 89.1, 437.0, 237.0, 157.0, 95.0, 977.0, 92.0, 187.0, 107.0, 137.0, 337.0, 107.0, 1007.0, 267.0, 157.0, 117.0, 267.0, 267.0, 80.0, 56.9, 64.0, 147.0, 307.0, 117.0, 337.0, 147.0, 49.0, 53.7, 59.0, 54.5, 82.0, 107.0, 80.0, 32.8, 207.0, 104.0, 86.9, 357.0, 49.0, 117.0, 207.0, 27.3, 37.1, 9017.0, 35.2, 82.0, 257.0, 117.0, 102.8, 96.7, 127.0, 847.0, 117.0, 52.0, 807.0, 217.0, 127.0, 55.0, 107.0, 46.2, 82.4, 65.2, 90.8, 7107.0, 417.0, 70.9, 69.9, 73.7, 157.0, 44.9, 157.0, 147.0, 417.0, 177.0, 57.0, 247.0, 157.0, 287.0, 70.3, 327.0, 59.1, 107.0, 407.0, 177.0, 107.0, 95.9, 377.0, 187.0, 52.5, 257.0, 137.0, 96.0, 237.0, 187.0, 227.0, 257.0, 64.9, 127.0, 92.1, 49.8, 317.0, 117.0, 75.0, 217.0, 287.0, 61.0, 187.0, 177.0, 157.0, 307.0, 50.0, 107.0, 9767.0, 66.0, 237.0, 217.0, 77.5, 79.0, 72.0, 102.0, 85.0, 197.0, 137.0, 167.0, 407.0, 177.0, 227.0, 117.0, 9637.0, 607.0, 327.0, 89.0, 337.0, 65.7, 217.0, 277.0, 137.0, 197.0, 93.0, 29.9, 317.0, 79.7, 157.0, 82.6, 347.0, 53.0, 157.0, 117.0, 80.0, 137.0, 91.4, 76.2, 57.0, 65.0, 427.0, 50.5, 51.0, 727.0, 267.0, 9167.0, 70.0, 137.0, 117.0, 84.0, 56.1, 1607.0, 417.0, 85.8, 98.2, 327.0, 43.4, 217.0, 227.0, 217.0, 1327.0, 167.0, 107.0, 46.0, 98.1, 167.0, 277.0, 101.0, 147.0, 77.9, 387.0, 147.0, 207.0, 167.0, 105.0, 74.1, 97.0, 227.0, 44.5, 90.5, 167.0, 317.0, 79.1, 837.0, 307.0, 247.0, 51.1, 237.0, 427.0, 977.0, 177.0, 227.0, 33.2, 287.0, 157.0, 147.0, 62.0, 127.0, 87.0, 83.5, 127.0, 177.0, 75.0, 91.0, 74.2, 107.0, 127.0, 107.0, 1407.0, 58.8, 83.7, 387.0, 137.0, 117.0, 42.2, 127.0, 477.0, 98.0, 157.0, 77.5, 377.0, 92.0, 217.0, 157.0, 64.0, 277.0, 95.0, 147.0, 607.0, 167.0, 104.5, 61.0, 107.0, 207.0, 65.5, 307.0, 167.0, 117.0, 96.0, 76.6, 237.0, 227.0, 73.0, 78.0, 127.0, 167.0, 257.0, 66.3, 73.5, 54.5, 137.0, 137.0, 64.8, 137.0, 987.0, 76.6, 47.0, 137.0, 237.0, 68.0, 79.0, 167.0, 137.0, 307.0, 102.0, 46.9, 147.0, 137.0, 79.2, 53.0, 94.0, 107.0, 38.9, 104.5, 72.7, 127.0, 727.0, 157.0, 53.5, 377.0, 327.0, 167.0, 81.9, 247.0, 93.0, 427.0, 307.0, 217.0, 137.0, 54.3, 49.5, 277.0, 68.2, 64.6, 88.6, 62.8, 127.0, 78.0, 247.0, 567.0, 100.5, 107.0, 577.0, 237.0, 69.0, 34.3, 297.0, 527.0, 81.7, 127.0, 147.0, 177.0, 147.0, 63.0, 62.3, 73.6, 64.1, 68.0, 137.0, 217.0, 82.0, 83.0, 72.0, 207.0, 117.0, 63.0, 117.0, 76.7, 167.0, 157.0, 76.0, 107.0, 56.0, 167.0, 257.0, 69.2, 377.0, 287.0, 104.2, 105.0, 117.0, 137.0, 387.0, 267.0, 64.0, 117.0, 247.0, 53.0, 147.0, 127.0, 80.9, 197.0, 64.7, 507.0, 187.0, 237.0, 247.0, 527.0, 277.0, 227.0, 757.0, 96.0, 377.0, 427.0, 117.0, 96.0, 107.0, 177.0, 44.0, 107.0, 127.0, 97.0, 53.0, 347.0, 102.1, 87.0, 197.0, 167.0, 49.0, 497.0, 72.0, 51.5, 267.0, 107.0, 59.0, 147.0, 167.0, 107.0, 217.0, 77.8, 157.0, 117.0, 267.0, 74.0, 227.0, 98.3, 77.1, 277.0, 59.0, 64.4, 52.0, 57.2, 127.0, 317.0, 81.0, 237.0, 89.7, 477.0, 52.5, 71.7, 51.0, 33.3, 277.0, 107.0, 50.2, 44.0, 33.2, 167.0, 137.0, 117.0, 277.0, 79.0, 197.0, 51.0, 227.0, 43.5, 65.0, 147.0, 147.0, 1537.0, 147.0, 217.0, 33.3, 157.0, 80.0, 147.0, 807.0, 147.0, 417.0, 167.0, 75.0, 117.0, 105.0, 317.0, 247.0, 77.5, 70.0, 117.0, 9567.0, 287.0, 62.4, 62.2, 7027.0, 77.0, 197.0, 85.1, 102.0, 48.5, 73.5, 727.0, 61.9, 607.0, 73.5, 127.0, 33.3, 157.0, 97.3, 137.0, 62.0, 54.0, 207.0, 103.0, 49.0, 907.0, 137.0, 307.0, 82.0, 93.0, 127.0, 85.0, 101.0, 147.0, 88.5, 107.0, 427.0, 59.9, 217.0, 647.0, 107.0, 117.0, 237.0, 82.0, 117.0, 103.7, 257.0, 177.0, 117.0, 247.0, 197.0, 89.8, 107.0, 54.3, 177.0, 147.0, 8317.0, 247.0, 287.0, 287.0, 91.5, 157.0, 167.0, 76.6, 167.0, 107.0, 407.0, 137.0, 277.0, 75.0, 85.9, 167.0, 67.0, 1667.0, 147.0, 257.0, 217.0, 217.0, 60.2, 62.2, 117.0, 217.0, 247.0, 697.0, 58.0, 81.9, 597.0, 97.0, 59.0, 92.0, 74.0, 49.0, 61.0, 79.2, 64.5, 97.0, 42.9, 67.7, 86.8, 477.0, 157.0, 137.0, 83.2, 137.0, 82.0, 41.0, 93.5, 67.0, 157.0, 147.0, 68.0, 82.0, 457.0, 67.0, 93.0, 207.0, 147.0, 127.0, 85.0, 257.0, 61.0, 71.4, 367.0, 100.8, 317.0, 287.0, 137.0, 117.0, 137.0, 71.8, 197.0, 38.3, 75.0, 42.0, 137.0, 54.0, 73.0, 137.0, 81.9, 127.0, 197.0, 117.0, 977.0, 62.5, 72.1, 43.9, 117.0, 79.0, 49.5, 66.0, 207.0, 127.0, 507.0, 62.0, 177.0, 507.0, 53.4, 49.5, 107.0, 53.5, 307.0, 207.0, 105.0, 49.3, 127.0, 297.0, 197.0, 93.0, 117.0, 367.0, 367.0, 187.0, 187.0, 74.3, 51.4, 29.8, 32.7, 127.0, 307.0, 177.0, 87.0, 237.0, 107.0, 257.0, 327.0, 317.0, 107.0, 437.0, 147.0, 157.0, 147.0, 237.0, 107.0, 87.0, 257.0, 207.0, 147.0, 597.0, 103.0, 197.0, 127.0, 102.2, 82.0, 30.6, 577.0, 167.0, 157.0, 33.3, 43.0, 157.0, 106.6, 167.0, 32.4, 117.0, 84.0, 247.0, 197.0, 59.0, 93.5, 247.0, 57.8, 82.0, 217.0, 87.1, 74.5, 417.0, 104.7, 33.0, 72.0, 177.0, 797.0, 73.9, 67.0, 63.4, 62.4, 167.0, 70.0, 487.0, 117.0, 267.0, 66.9, 167.0, 357.0, 147.0, 67.0, 687.0, 82.0, 82.0, 317.0, 56.1, 237.0, 127.0, 167.0, 127.0, 297.0, 117.0, 257.0, 101.5, 387.0, 547.0, 227.0, 297.0, 117.0, 86.7, 86.0, 237.0, 7847.0, 167.0, 79.0, 277.0, 107.0, 157.0, 147.0, 1187.0, 227.0, 767.0, 367.0, 107.0, 127.0, 33.3, 277.0, 557.0, 217.0, 137.0, 69.3, 69.0, 627.0, 117.0, 90.8, 63.9, 82.0, 197.0, 357.0, 48.9, 197.0, 101.0, 187.0, 277.0, 157.0, 107.0, 267.0, 457.0, 127.0, 9530.0, 227.0, 77.8, 40.0, 137.0, 197.0, 92.0, 72.3, 107.0, 117.0, 437.0, 237.0, 177.0, 137.0, 197.0, 147.0, 217.0, 51.0, 517.0, 137.0, 75.9, 74.0, 65.9, 80.9, 627.0, 277.0, 117.0, 477.0, 107.0, 267.0, 59.2, 102.0, 105.0, 137.0, 92.9, 73.5, 56.9, 70.0, 127.0, 177.0, 187.0, 237.0, 187.0, 72.4, 84.4, 137.0, 187.0, 237.0, 147.0, 107.0, 117.0, 88.0, 117.0, 87.0, 127.0, 97.0, 137.0, 117.0, 52.8, 87.0, 36.5, 29.9, 307.0, 92.0, 127.0, 63.8, 247.0, 71.7, 101.0, 117.0, 47.1, 107.0, 107.0, 91.0, 65.0, 88.2, 337.0, 85.6, 35.1, 74.9, 387.0, 45.4, 63.9, 687.0, 617.0, 23.6, 72.0, 267.0, 66.0, 197.0, 69.7, 187.0, 62.7, 177.0, 247.0, 40.0, 54.5, 407.0, 377.0, 88.9, 137.0, 167.0, 84.0, 117.0, 77.9, 107.0, 55.0, 257.0, 207.0, 43.8, 227.0, 49.3, 52.0, 117.0, 83.0, 9707.0, 217.0, 277.0, 117.0, 66.0, 42.0, 85.0, 85.0, 77.0, 387.0, 59.9, 237.0, 277.0, 102.4, 74.0, 187.0, 127.0, 477.0, 157.0, 367.0, 76.7, 597.0, 137.0, 137.0, 80.0, 167.0, 105.2, 107.0, 65.6, 167.0, 59.0, 41.0, 106.9, 247.0, 61.0, 64.0, 237.0, 137.0, 317.0, 137.0, 90.5, 93.0, 297.0, 58.9, 117.0, 207.0, 377.0, 55.0, 8607.0, 277.0, 35.0, 70.6, 107.0, 147.0, 127.0, 70.0, 177.0, 69.4, 54.0, 137.0, 137.0, 63.3, 102.0, 347.0, 117.0, 337.0, 187.0, 53.9, 137.0, 72.5, 73.0, 87.0, 60.9, 117.0, 107.0, 167.0, 103.0, 907.0, 68.0, 127.0, 137.0, 90.6, 347.0, 7517.0, 127.0, 247.0, 237.0, 107.0, 54.5, 327.0, 99.7, 147.0, 227.0, 92.0, 65.7, 57.9, 82.2, 297.0, 73.82, 82.0, 103.0, 477.0, 227.0, 62.0, 65.0, 59.0, 54.0, 217.0, 367.0, 63.0, 46.5, 33.2, 157.0, 73.8, 157.0, 197.0, 51.5, 127.0, 297.0, 237.0, 86.3, 255.0, 87.0, 58.0, 117.0, 86.0, 347.0, 317.0, 98.2, 137.0, 437.0, 267.0, 247.0, 187.0, 137.0, 297.0, 267.0, 187.0, 43.0, 117.0, 167.0, 127.0, 49.0, 46.5, 101.3, 42.0, 58.0, 28.5, 64.3, 197.0, 36.2, 417.0, 297.0, 177.0, 117.0, 507.0, 95.0, 197.0, 167.0, 137.0, 117.0, 607.0, 347.0, 59.0, 307.0, 187.0, 427.0, 187.0, 56.5, 297.0, 67.0, 387.0, 167.0, 577.0, 177.0, 66.6, 117.0, 137.0, 167.0, 63.5, 107.0, 227.0, 92.0, 59.8, 56.5, 103.0, 43.0, 157.0, 117.0, 147.0, 477.0, 72.0, 102.0, 85.0, 67.7, 62.0, 397.0, 197.0, 107.0, 157.0, 94.7, 467.0, 84.0, 197.0, 46.0, 157.0, 73.0, 63.9, 98.0, 80.6, 93.0, 277.0, 857.0, 118.0, 117.0, 177.0, 247.0, 83.8, 157.0, 377.0, 177.0, 96.0, 187.0, 84.1, 227.0, 167.0, 127.0, 84.0, 79.6, 147.0, 117.0, 63.2, 467.0, 102.0, 84.0, 66.0, 81.0, 32.8, 147.0, 177.0, 89.6, 157.0, 147.0, 67.5, 91.2, 137.0, 69.0, 70.9, 46.0, 147.0, 247.0, 1767.0, 48.5, 117.0, 107.0, 60.0, 127.0, 32.8, 72.8, 107.0, 72.0, 187.0, 137.0, 187.0, 106.0, 68.6, 9207.0, 147.0, 52.1, 227.0, 337.0, 92.0, 307.0, 357.0, 54.9, 50.0, 33.0, 167.0, 267.0, 46.0, 297.0, 48.3, 247.0, 577.0, 397.0, 747.0, 55.0, 107.0, 147.0, 1507.0, 117.0, 117.0, 117.0, 86.0, 102.0, 85.0, 127.0, 71.5, 137.0, 107.0, 33.1, 82.0, 147.0, 147.0, 83.0, 39.0, 38.1, 66.9, 167.0, 100.0, 57.4, 117.0, 60.5, 81.0, 557.0, 307.0, 84.5, 66.0, 127.0, 71.7, 106.1, 137.0, 167.0, 117.0, 227.0, 227.0, 307.0, 97.0, 137.0, 9207.0, 53.0, 177.0, 237.0, 77.1, 347.0, 9627.0, 197.0, 127.0, 69.0, 98.4, 247.0, 257.0, 115.0, 87.0, 54.0, 98.0, 137.0, 86.0, 157.0, 187.0, 237.0, 39.0, 147.0, 81.9, 91.6, 687.0, 277.0, 82.0, 96.9, 147.0, 257.0, 117.0, 117.0, 177.0, 91.8, 75.0, 105.0, 71.0, 87.0, 68.0, 237.0, 74.7, 207.0, 337.0, 117.0, 82.7, 217.0, 72.9, 267.0, 35.0, 117.0, 247.0, 51.1, 357.0, 94.5, 177.0, 197.0, 69.4, 70.2, 102.5, 177.0, 86.0, 407.0, 197.0, 76.9, 447.0, 72.0, 117.0, 86.0, 49.7, 107.0, 117.0, 537.0, 90.6, 207.0, 127.0, 104.2, 77.0, 49.0, 177.0, 69.5, 106.0, 227.0, 367.0, 257.0, 257.0, 127.0, 127.0, 97.8, 487.0, 257.0, 307.0, 49.0, 98.0, 117.0, 31.0, 167.0, 157.0, 54.8, 207.0, 93.6, 187.0, 137.0, 43.0, 101.0, 97.5, 102.0, 66.2, 50.7, 137.0, 63.0, 86.1, 137.0, 56.5, 147.0, 56.0, 147.0, 277.0, 77.0, 127.0, 317.0, 35.5, 103.0, 137.0, 33.3, 217.0, 76.6, 237.0, 64.0, 36.5, 157.0, 257.0, 67.3, 207.0, 104.0, 287.0, 657.0, 337.0, 117.0, 127.0, 207.0, 106.0, 137.0, 50.9, 55.0, 107.0, 107.0, 197.0, 68.2, 86.0, 92.0, 102.0, 247.0, 317.0, 227.0, 92.5, 78.7, 297.0, 68.8, 127.0, 137.0, 427.0, 104.7, 85.0, 107.0, 537.0, 48.9, 78.0, 100.0, 117.0, 33.3, 65.0, 101.0, 807.0, 277.0, 287.0, 217.0, 64.3, 48.0, 87.0, 377.0, 106.6, 106.7, 127.0, 59.9, 107.0, 137.0, 92.0, 147.0, 54.5, 1007.0, 61.2, 107.0, 117.0, 157.0, 167.0, 34.6, 307.0, 117.0, 93.0, 147.0, 50.9, 237.0, 557.0, 107.0, 66.0, 287.0, 53.0, 84.9, 247.0, 87.8, 80.4, 45.4, 69.3, 77.9, 127.0, 92.6, 537.0, 5507.0, 72.0, 74.9, 73.0, 62.9, 357.0, 82.0, 47.0, 147.0, 177.0, 101.0, 427.0, 62.9, 787.0, 82.0, 117.0, 227.0, 57.0, 63.0, 227.0, 67.0, 127.0, 107.0, 157.0, 71.0, 167.0, 217.0, 89.0, 127.0, 157.0, 79.0, 217.0, 147.0, 106.0, 107.0, 107.0, 75.3, 59.7, 78.0, 82.0, 277.0, 347.0, 177.0, 45.2, 48.0, 106.0, 237.0, 77.0, 94.0, 58.9, 137.0, 88.9, 417.0, 177.0, 177.0, 517.0, 487.0, 277.0, 80.3, 77.0, 32.6, 55.9, 76.0, 9467.0, 107.0, 187.0, 117.0, 217.0, 127.0, 267.0, 62.0, 102.0, 287.0, 147.0, 38.0, 227.0, 107.0, 72.9, 917.0, 367.0, 107.0, 117.0, 217.0, 52.0, 247.0, 85.0, 247.0, 74.9, 49.0, 707.0, 117.0, 107.0, 33.0, 63.5, 237.0, 57.1, 32.8, 67.0, 147.0, 177.0, 95.0, 33.0, 107.0, 88.3, 187.0, 

In [99]:
l.insert(11,"NT2",price7)
l

,POSTED_BY,UNDER_CONSTRUCTION,RERA,BHK_NO.,BHK_OR_RK,SQUARE_FT,READY_TO_MOVE,RESALE,City,LONGITUDE,LATITUDE,NT2,TARGET(PRICE_IN_LACS)
15,Dealer,1,1,3,BHK,1394.117647,0,1,Noida,28.429614,77.481711,78.1,71.1
17,Dealer,1,1,3,BHK,2124.896706,0,1,Bangalore,12.885500,77.563800,187.0,180.0
19,Dealer,0,1,3,BHK,2178.649237,1,1,Bangalore,13.092356,77.613468,127.0,120.0
22,Dealer,0,1,3,BHK,1310.147689,1,1,Noida,28.504100,77.381557,62.0,55.0
43,Dealer,0,1,3,BHK,1274.924779,1,1,Mumbai,22.803593,83.755013,257.0,250.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
29386,Dealer,0,1,3,BHK,1727.115717,1,1,Bangalore,12.984700,77.549100,147.0,140.0
29399,Dealer,0,1,3,BHK,1850.149391,1,1,Ghaziabad,28.919600,76.897200,87.5,80.5
29409,Dealer,0,1,4,BHK,5399.568035,1,1,Surat,21.143354,72.770931,407.0,400.0
29435,Dealer,0,1,4,BHK,2189.160468,1,1,Chandigarh,30.662283,76.822397,89.4,82.4
29443,Dealer,0,1,3,BHK,1161.194975,1,1,Maharashtra,19.111438,72.878724,227.0,220.0